# -*- coding: utf-8 -*-
"""dreamfall.art 5 reels. Shot boundaries from measured frame-diff cuts."""

DF_STYLE = ("1990s Hollywood romantic drama film still, shot on 35mm Kodak Vision3 500T, 9:16 vertical, "
            "Upper East Side Manhattan in late autumn, soft warm tungsten interiors and grey overcast daylight, "
            "fine film grain, gentle halation, muted palette of burgundy, cream, champagne and forest green, "
            "shallow depth of field, natural skin texture, no text, no watermark")
DF_ANI_STYLE = ("photorealistic miniature film set, real fluffy {ANIMAL}s wearing tiny tailored 1990s clothes, "
                "1990s Hollywood romance film look, 35mm grain, warm tungsten light, 9:16 vertical, wholesome and cute")

BRUNETTE = "a woman in her twenties with long voluminous dark-brown blowout hair, grey-green eyes and glossy nude lips"
MAN = "a man in his late twenties with thick swept-back dark hair, wearing a black suit jacket over an open-collar white shirt"
BLONDE = "a woman with long sleek platinum-blonde hair and a large diamond statement necklace"
A_BRUN = "a chocolate-brown {ANIMAL} heroine"
A_MAN = "a golden {ANIMAL} gentleman in a tiny black suit jacket and open white shirt"
A_BLONDE = "a long-haired cream angora {ANIMAL} rival wearing a tiny diamond necklace"

DF_CAST = [("브루넷 여주인공", "초콜릿색 {ANIMAL} (여주인공)"), ("남자 (David)", "골든 {ANIMAL} 신사, 검은 수트+흰 셔츠"),
           ("금발 약혼녀", "크림색 장모(앙고라) {ANIMAL} — 긴 털이 금발 역할"),
           ("동양인 친구(3화)", "정글리안(드워프) {ANIMAL}, 올리브 블레이저+벽돌폰"), ("엑스트라", "회색 노년 {ANIMAL} 부부 등")]

DF_TECH_COMMON = [
    ("숏-리버스숏 (Shot / reverse shot)", "두 사람 대화를 A 얼굴 → B 얼굴로 번갈아 보여 줌. 180도 규칙(카메라가 두 사람을 잇는 선을 넘지 않음)을 지켜 시선 방향이 일관됨"),
    ("리액션 샷 우선 (Reaction-first cutting)", "말하는 사람보다 '듣는 사람의 표정'에 더 오래 머묾 → 감정 전달"),
    ("인서트 (Insert)", "손, 카드, 컵 같은 소품 클로즈업을 1초 안팎으로 끼워 넣어 스토리 정보를 줌"),
    ("90년대 필름 룩 (Period look)", "35mm 입자, 따뜻한 텅스텐 조명, 버건디·크림·샴페인 색 배합. 로맨스 영화 한 장면처럼 보이게 함"),
    ("에피소드형 클리프행어 (Serial cliffhanger)", "마지막 샷에 반전 정보를 던지고 끝 → 'PART N 페이지에서 보기' 캡션으로 프로필 방문 유도"),
]

PAGE_DF2 = {
    "key": "df2", "file": "df_DctKaR8N7VR", "rank": "dreamfall 링크 ①",
    "title": "ACROSS THE STREET — Episode 2 (길 건너 창문, 전화)",
    "url": "https://www.instagram.com/dreamfall.art/reel/DctKaR8N7VR/",
    "metrics": "좋아요 2,151,373 · 댓글 14,731 · 2026-08-31 업로드 (시리즈 최고 반응)",
    "spec": "35.2초 · 1440×2560 · 30fps · 실측 컷 19개 · 평균 샷 1.76초",
    "music": "음원명 메타데이터 없음 (후속 3·4화는 Mitski 'My Love Mine All Mine'). 대사 음성 있음 — 아래 샷별 대사는 Whisper 인식(타이밍 ±1초 오차, 화자는 화면 기준 추정)",
    "tool": "Made in @higgsfield.ai (캡션 명시)",
    "hook": "0~1초: 센트럴파크 단풍이 보이는 창가에서 수건 차림으로 머리를 빗는 뒷모습 → 1~3초 정면에서 '헉' 놀라는 얼굴. 무엇을 봤는지 궁금하게 만듦",
    "formula": [
        "① 0~3.2s 사적인 순간 + 충격 리액션 (무엇을 봤지?)",
        "② 3.2~11.8s 창 너머 남자 공개 → 숨기/훔쳐보기 핑퐁 (리어 윈도우식 관음 구도)",
        "③ 13.3~27.5s 전화벨 → 창문 사이 통화 (대사 핑퐁)",
        "④ 28.9~34.8s 남자 뒤에 금발 여성 등장, 볼에 키스 = 반전 → 3화로 연결",
    ],
    "why": [
        "대사가 짧고 쉬운 영어라 자막 없이도 이해됨",
        "두 창문을 잇는 '길 건너' 공간 설정이 한 장면으로 이해됨 (23.6s 외부 설정 샷)",
        "평균 1.76초의 빠른 컷 = 90년대 영화 톤인데 속도는 릴스 속도",
        "마지막 3초 반전(다른 여자) → 댓글 논쟁 폭발 (댓글 1.4만)",
    ],
    "techniques": DF_TECH_COMMON + [
        ("POV / OTS 창 너머 샷", "그녀 머리를 전경에 걸치고 길 건너 창 속 남자를 보여 줌 → 두 사람의 물리적 거리 강조"),
        ("창틀 전경 프레이밍 (Frame within frame)", "남자와 여자 모두 창틀 막대가 화면 하단을 가로지름 = 유리를 사이에 둔 관계"),
        ("설정 샷 늦게 쓰기 (Late establishing shot)", "건물 외관은 23.6s에야 1초만 보여 줌. 감정을 먼저, 지리는 나중"),
    ],
    "shots": [
        {"t0": 0.0, "t1": 1.0, "size": "WS (뒷모습)", "angle": "눈높이, 방 안", "move": "고정", "grid": "1,4,7",
         "comp": "창문 중앙, 인물 뒷모습 중앙. 좌우 붉은 벨벳 커튼, 창밖 센트럴파크 단풍+맨해튼 스카이라인",
         "action": "허리에 흰 수건을 두르고 창가에서 머리를 빗음 (등 노출, 뒷모습만)", "line": "—", "trans": "하드컷",
         "sfx": "도시 앰비언스, 빗질 소리", "models": "Veo / Seedance (창밖 풍경 원근)",
         "img": f"wide shot from behind, {BRUNETTE} with a white bath towel wrapped around her, standing at a tall window brushing her hair, red velvet drapes, Central Park autumn foliage and the Manhattan skyline outside, tasteful, back view only",
         "vid": "she slowly brushes her long hair, drapes sway slightly, camera still",
         "ani": f"wide shot from behind, {A_BRUN} wrapped in a tiny fluffy white bath towel like a burrito, standing at a tall window brushing its fur with a tiny wooden brush, red velvet drapes, Central Park autumn view"},
        {"t0": 1.0, "t1": 3.2, "size": "MCU", "angle": "정면", "move": "고정", "grid": "1,4,7",
         "comp": "얼굴 상단 1/3, 쇄골 아래 수건 라인. 배경 금빛 벽+촛대 보케",
         "action": "무표정으로 빗질하다 창밖을 보고 입을 크게 벌려 놀람(2.25s) → 빗으로 가슴을 가림", "line": "(헉)", "trans": "하드컷",
         "sfx": "짧은 숨 들이쉼", "models": "Hailuo(MiniMax) (놀람 표정) / Kling",
         "img": f"medium close-up, {BRUNETTE} wrapped in a white towel, holding a wooden paddle hairbrush, looking out of frame, gilded room with candle bokeh",
         "vid": "she brushes her hair, suddenly notices something across the street, gasps with her mouth wide open and clutches the brush to her chest",
         "ani": f"medium close-up, {A_BRUN} in a tiny white towel holding a tiny hairbrush, gasps in surprise with mouth wide open, gilded room"},
        {"t0": 1.0 + 2.2, "t1": 3.8, "size": "POV/OTS", "angle": "그녀 시점, 수평", "move": "고정", "grid": "4,5,7,8",
         "comp": "왼쪽 전경 그녀 머리카락(흐림), 오른쪽 길 건너 건물 창문 속 남자 전신",
         "action": "남자가 자기 창가에 서서 이쪽을 보고 있음", "line": "—", "trans": "하드컷",
         "sfx": "—", "models": "Seedance / Veo",
         "img": f"over-the-shoulder shot past blurred brown hair, across a narrow Manhattan street a man in a suit standing in the window of a pale stone building opposite, looking back",
         "vid": "the man stands still in his window looking over; her hair sways in the foreground",
         "ani": f"over-the-shoulder past blurred brown fur, across the street {A_MAN} standing in the window of the opposite building"},
        {"t0": 3.8, "t1": 4.8, "size": "MS", "angle": "눈높이", "move": "고정", "grid": "0,3,4,6,7",
         "comp": "왼쪽 붉은 커튼, 그녀가 커튼 뒤로 몸을 숨김. 샹들리에 보케",
         "action": "커튼 뒤로 황급히 숨음", "line": "—", "trans": "하드컷", "sfx": "커튼 스치는 소리",
         "models": "Kling", "img": f"{BRUNETTE} in a white towel hiding behind a red velvet curtain, only her back and hair visible, chandelier bokeh",
         "vid": "she quickly steps behind the curtain to hide", "ani": f"{A_BRUN} in a towel hiding behind a red velvet curtain"},
        {"t0": 4.8, "t1": 6.8, "size": "MCU", "angle": "정면, 유리 너머", "move": "고정", "grid": "1,4,7",
         "comp": "남자 얼굴 중앙, 하단에 창틀 가로 막대. 뒤는 금빛 방",
         "action": "무표정으로 응시하다 입꼬리가 살짝 올라감", "line": "—", "trans": "하드컷", "sfx": "—",
         "models": "Hailuo(MiniMax) (미세 미소)", "img": f"medium close-up of {MAN} standing behind a window pane, white window sill bar across the bottom of frame, gilded room behind",
         "vid": "he stares calmly, then a faint smirk appears", "ani": f"medium close-up of {A_MAN} behind a window pane, sill bar across the bottom, faint smirk"},
        {"t0": 6.8, "t1": 8.0, "size": "MS", "angle": "눈높이", "move": "고정", "grid": "0,3,4,6",
         "comp": "왼쪽 커튼 가장자리, 그녀가 어깨 너머로 빼꼼",
         "action": "커튼 옆으로 고개를 내밀어 보고 입술을 깨물며 수줍게 웃음", "line": "—", "trans": "하드컷", "sfx": "—",
         "models": "Hailuo(MiniMax)", "img": f"{BRUNETTE} peeking out from behind a red curtain over her bare shoulder, towel, shy smile",
         "vid": "she peeks out, bites her lip and smiles shyly", "ani": f"{A_BRUN} peeking out from behind a red curtain, shy smile"},
        {"t0": 8.0, "t1": 10.4, "size": "OTS", "angle": "그녀 뒤", "move": "고정", "grid": "3,4,5,6,7",
         "comp": "전경 그녀 옆얼굴, 원경 길 건너 창 속 남자 작게",
         "action": "다시 창밖을 보며 옆얼굴 공개(9.25s)", "line": "—", "trans": "하드컷", "sfx": "—",
         "models": "Seedance", "img": f"over-the-shoulder profile of {BRUNETTE}, across the street the man small in his window",
         "vid": "she turns her profile toward the window, gazing", "ani": f"over-the-shoulder profile of {A_BRUN}, across the street the golden {{ANIMAL}} small in his window"},
        {"t0": 10.4, "t1": 11.8, "size": "MCU", "angle": "살짝 하이", "move": "고정", "grid": "1,4,7",
         "comp": "남자가 고개 숙이고 턱에 손", "action": "아래를 보며 턱을 만지고 웃음", "line": "—", "trans": "하드컷",
         "sfx": "—", "models": "Hailuo(MiniMax)", "img": f"{MAN} looking down, touching his chin, amused smile",
         "vid": "he looks down, strokes his chin and smiles to himself", "ani": f"{A_MAN} looking down, touching his chin, amused"},
        {"t0": 11.8, "t1": 13.3, "size": "OTS 뒷머리", "angle": "뒤", "move": "고정", "grid": "0,1,3,4,6,7",
         "comp": "그녀 뒷머리가 화면 대부분", "action": "창 쪽을 보며 서 있음 → 전화벨", "line": "(전화벨)", "trans": "하드컷",
         "sfx": "90년대 유선전화 벨 (13.4s 온셋)", "models": "Seedance",
         "img": f"from behind, the back of {BRUNETTE}'s long hair filling the frame, a window across the street", "vid": "she stands still, then reacts to a ringing phone",
         "ani": f"from behind, {A_BRUN}'s fluffy back filling the frame, window across the street"},
        {"t0": 13.3, "t1": 14.7, "size": "WS", "angle": "눈높이", "move": "고정", "grid": "3,4,5,6,7,8",
         "comp": "넓은 금빛 방, 아치형 창, 흰 목욕가운 차림으로 전화기 쪽으로 걸어감",
         "action": "맨발로 걸어가 수화기를 듦", "line": "—", "trans": "하드컷", "sfx": "벨 계속",
         "models": "Veo / Seedance", "img": f"wide shot of a lavish gilded apartment with arched windows over Central Park, {BRUNETTE} in a white bathrobe walking barefoot to a side table phone",
         "vid": "she walks across the room and picks up the phone", "ani": f"wide shot of a lavish miniature apartment, {A_BRUN} in a tiny white bathrobe walking to a tiny phone"},
        {"t0": 14.7, "t1": 16.4, "size": "CU", "angle": "정면", "move": "고정", "grid": "1,4,7",
         "comp": "얼굴 화면 가득, 왼쪽 크림색 수화기", "action": "수화기를 귀에 대고 말함", "line": "\"How did you get this number?\"",
         "trans": "하드컷", "sfx": "—", "models": "Veo (립싱크) / Kling Lip-sync",
         "img": f"close-up of {BRUNETTE} holding a cream 1990s landline handset to her ear", "vid": "she speaks into the phone: 'How did you get this number?'",
         "ani": f"close-up of {A_BRUN} holding a cream landline handset to its ear, speaking"},
        {"t0": 16.4, "t1": 17.7, "size": "CU (창틀 전경)", "angle": "정면", "move": "고정", "grid": "1,4,7",
         "comp": "하단 창틀 막대, 수화기 코드", "action": "듣는 표정", "line": "(남) \"I have my ways.\"", "trans": "하드컷",
         "sfx": "—", "models": "Hailuo(MiniMax)", "img": f"close-up of {BRUNETTE} on the phone seen through a window, white sill bar across the bottom",
         "vid": "she listens, eyes narrowing slightly", "ani": f"close-up of {A_BRUN} on the phone through a window, sill bar across the bottom"},
        {"t0": 17.7, "t1": 18.7, "size": "CU", "angle": "정면", "move": "고정", "grid": "1,4,7",
         "comp": "남자 얼굴, 왼쪽 수화기", "action": "능글맞게 말함", "line": "(여·화면 밖) \"I threw your number away.\" → (남) \"I know.\"", "trans": "하드컷",
         "sfx": "—", "models": "Veo (립싱크)", "img": f"close-up of {MAN} holding a cream landline handset, half-lidded confident look",
         "vid": "he answers into the phone with a lazy confident smile", "ani": f"close-up of {A_MAN} holding a landline handset, confident look"},
        {"t0": 18.7, "t1": 23.6, "size": "CU (창틀 전경)", "angle": "정면", "move": "고정 (롱테이크 4.9s)", "grid": "1,4,7",
         "comp": "그녀 얼굴, 하단 창틀", "action": "눈을 굴리다 따지듯 말함", "line": "(여) \"How?\" / (남) \"You didn't call.\" / (남) \"Five minutes.\" / (여) \"For what?\"",
         "trans": "하드컷", "sfx": "—", "models": "Veo (립싱크 롱테이크)",
         "img": f"close-up of {BRUNETTE} on the phone behind a window, sill bar across the bottom, skeptical expression",
         "vid": "she talks on the phone, rolls her eyes, skeptical then curious", "ani": f"close-up of {A_BRUN} on the phone behind a window, skeptical"},
        {"t0": 23.6, "t1": 24.6, "size": "EWS 설정 샷", "angle": "건너편 높이", "move": "고정", "grid": "1,4,7",
         "comp": "벽돌 건물 외벽, 가운데 창 속 전화하는 남자", "action": "통화 중", "line": "\"Completely sincere.\"", "trans": "하드컷",
         "sfx": "거리 소음", "models": "Seedance / Veo",
         "img": "exterior of a red-brick Upper East Side building, a single white-framed sash window, a man inside on the phone", "vid": "he talks on the phone inside the window, curtains still",
         "ani": "exterior of a miniature red-brick building, a white-framed window with the golden {ANIMAL} gentleman inside on the phone"},
        {"t0": 24.6, "t1": 26.5, "size": "WS", "angle": "눈높이", "move": "고정", "grid": "3,4,6,7",
         "comp": "화려한 방, 수건 차림으로 서서 통화", "action": "수화기를 들고 서서 고민", "line": "\"To apologize.\"", "trans": "하드컷",
         "sfx": "—", "models": "Veo", "img": f"wide shot, {BRUNETTE} wrapped in a white towel standing beside a lamp table holding a corded phone, opulent room",
         "vid": "she stands holding the phone, thinking", "ani": f"wide shot, {A_BRUN} in a tiny towel standing with a corded phone, opulent room"},
        {"t0": 26.5, "t1": 27.5, "size": "MCU (유리 너머)", "angle": "정면", "move": "고정", "grid": "1,4,7",
         "comp": "남자, 유리창 반사", "action": "환하게 웃음", "line": "\"Five minutes.\"", "trans": "하드컷", "sfx": "—",
         "models": "Hailuo(MiniMax)", "img": f"{MAN} on the phone seen through a window glass with reflections, charming grin",
         "vid": "he grins widely into the phone", "ani": f"{A_MAN} on the phone through window glass, charming grin"},
        {"t0": 27.5, "t1": 28.9, "size": "WS", "angle": "눈높이", "move": "고정", "grid": "4,5,7,8",
         "comp": "방 안쪽으로 걸어가는 뒷모습", "action": "전화를 끊고 방 안쪽으로 걸어감", "line": "—", "trans": "하드컷", "sfx": "수화기 내려놓는 소리",
         "models": "Seedance", "img": f"wide shot, {BRUNETTE} walking away toward the bedroom in an opulent apartment", "vid": "she walks away across the room",
         "ani": f"wide shot, {A_BRUN} walking away across an opulent miniature room"},
        {"t0": 28.9, "t1": 34.8, "size": "MCU → 2S", "angle": "정면, 유리 너머", "move": "고정 (롱테이크 5.9s)", "grid": "0,1,3,4",
         "comp": "남자 중앙 → 31s 금발 여성이 뒤 왼쪽에서 들어옴 → 34s 볼 키스",
         "action": "웃으며 창밖을 보다 금발이 어깨에 손을 얹음, 볼에 키스",
         "line": "\"Who was that?\" / \"Business.\" / \"Now?\" / \"I have a meeting.\"", "trans": "하드컷 → 엔딩",
         "sfx": "샹들리에 룸톤", "models": "Veo (2인 대사) / Seedance",
         "img": f"medium shot through a window, {MAN} smiling, behind him {BLONDE} in a champagne satin dress stepping in and resting a hand on his shoulder, crystal chandelier",
         "vid": "he smiles; the blonde woman walks in behind him, asks who that was, he says business, she kisses his cheek",
         "ani": f"medium shot through a window, {A_MAN} smiling, {A_BLONDE} steps in behind him and kisses his cheek, crystal chandelier"},
        {"t0": 34.8, "t1": 35.2, "size": "꼬리", "angle": "—", "move": "—", "grid": "4", "comp": "마지막 0.4초", "action": "엔딩 프레임",
         "line": "—", "trans": "끝 (루프)", "sfx": "—", "models": "편집", "img": "", "vid": "", "ani": ""},
    ],
    "cast": DF_CAST, "rotate": False,
}
