# -*- coding: utf-8 -*-
"""dreamfall Episode 1 + The Gentleman."""
from data_df import DF_CAST, DF_TECH_COMMON, BRUNETTE, MAN, BLONDE, A_BRUN, A_MAN, A_BLONDE
from data_df2 import S, NOIMG

PAGE_DF1 = {
    "key": "df1", "file": "df_DcqjfZvNKTr", "rank": "dreamfall 링크 ④",
    "title": "ACROSS THE STREET — Episode 1 (5번가 충돌, 명함을 버리다)",
    "url": "https://www.instagram.com/dreamfall.art/reel/DcqjfZvNKTr/",
    "metrics": "좋아요 607,606 · 댓글 5,748 · 2026-08-30 업로드",
    "spec": "27.2초 · 1440×2560 · 30fps · 실측 컷 8개 · 평균 샷 3.0초",
    "music": "음원명 메타데이터 없음. 대사: \"Oh, I'm so sorry. I'm, um...\" / \"David?\" (Whisper)",
    "tool": "Made in @higgsfield.ai · 캡션에서 'DREAM' 댓글 → 프롬프트 커뮤니티 유도",
    "hook": "0~2.8초: 눈 내린 5번가, 책을 한가득 안은 여자와 남자가 부딪혀 책이 쏟아짐 = 로맨틱코미디의 고전 '미트 큐트' 공식을 2초 안에",
    "formula": [
        "① 0~2.8s 충돌 (미트 큐트)",
        "② 2.8~8.9s 손이 닿는 인서트 → 남자 클로즈업 → 머리 넘기며 미소 (설렘 최고점)",
        "③ 8.9~16.2s 가게에서 금발 여자친구 등장, 남자가 팔을 내어 줌 (급반전)",
        "④ 16.2~25s 떠나는 커플을 보다가 책 사이 명함 발견",
        "⑤ 25~27s 명함을 쓰레기통에 던지고 걸어감 = 자존심 엔딩 → 2화로",
    ],
    "why": [
        "누구나 아는 로코 공식 + 90년대 뉴욕 겨울 = 향수 자극",
        "명함 버리는 엔딩: '잘했다 vs 아깝다' 댓글 논쟁",
        "2화 대사 'I threw your number away'로 이어지는 시리즈 설계 (떡밥 회수)",
        "대사 2줄뿐 — 행동만으로 스토리 전달",
    ],
    "techniques": DF_TECH_COMMON + [
        ("미트 큐트 (Meet-cute)", "우연한 충돌로 두 주인공이 만나는 로맨스 장르 공식"),
        ("자연 와이프 (Natural wipe)", "8.75s, 10.75s 행인이 카메라 앞을 지나가며 화면을 가림 → 롱테이크 안에서 리듬 생성, AI 클립 이음새도 숨김"),
        ("POV 리빌 인서트", "20.2~25s 그녀 얼굴 아래에 명함이 올라옴 — 한 프레임에 얼굴+정보"),
        ("뒷모습 엔딩 (Walk-away ending)", "카메라에서 멀어지는 뒷모습 + 원경의 커플 = 두 갈래 길"),
    ],
    "shots": [
        S(0.0, 2.8, "MS 워킹", "정면", "고정 → 충돌 순간 흔들림", "1,4,7", "여자 중앙, 가슴에 책 더미. 배경 노란 택시·스팀·크리스마스 쇼윈도",
          "걷다가 오른쪽에서 들어온 남자와 부딪혀 책이 쏟아짐(1.75~2.25s)", "(여) \"Oh, I'm so sorry...\"", "하드컷", "거리 소음, 책 떨어지는 쿵",
          "Kling (충돌 물리) / Seedance",
          f"medium shot, {BRUNETTE} in a houndstooth wool blazer walking on snowy Fifth Avenue hugging a stack of books and magazines, yellow cabs, steam from street vents, lit holiday shop windows",
          f"she walks toward camera; {MAN} enters from the right and bumps into her, books spill onto the wet pavement", f"medium shot, {A_BRUN} in a tiny houndstooth blazer hugging a stack of tiny books on snowy Fifth Avenue, bumped by {A_MAN}, books spill"),
        S(2.8, 4.3, "인서트", "탑", "고정", "3,4,5,7", "젖은 보도 위 책 표지, 두 사람 손가락이 같은 책 위에서 닿음", "손끝이 닿음", "—", "하드컷", "음악 강조음",
          "Kling / Seedance", "insert close-up of a man's and a woman's fingers touching over the same fallen book on wet pavement", "their fingertips touch and pause",
          "insert close-up of a golden paw and a chocolate paw touching over the same tiny book on wet pavement"),
        S(4.3, 5.6, "CU", "살짝 로우", "고정", "1,2,4,5", "남자 얼굴 오른쪽, 초록 눈", "그녀를 바라봄", "(여) \"I'm, um...\"", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {MAN} crouching on the street, looking at her with green eyes", "he looks at her, captivated", f"close-up of {A_MAN} crouching, captivated"),
        S(5.6, 8.9, "2S", "눈높이", "고정", "0,1,3,4", "왼쪽 여자, 오른쪽 전경 남자 옆모습", "책을 건네받으며 머리를 귀 뒤로 넘기고 미소 (명함 몰래 끼움)", "—", "하드컷", "—", "Hailuo(MiniMax) / Kling",
          f"two-shot, {BRUNETTE} tucking her hair behind her ear and smiling as {MAN} hands her a book", "she tucks her hair and smiles, he hands back the book", f"two-shot, {A_BRUN} tucking its ear fur and smiling as {A_MAN} hands over a book"),
        S(8.9, 16.2, "WS 롱테이크", "눈높이", "고정, 행인 와이프 2회", "0,1,2,3,4,5,6,7,8", "고급 부티크 입구, 왼쪽 여자·오른쪽 남자, 가운데 금발 등장",
          "검은 가죽 트렌치 금발이 쇼핑백 들고 나옴 → 남자가 팔을 내어 줌", "(금발) \"David?\"", "하드컷", "문 종소리, 행인",
          "Seedance (다인물·행인)", f"wide shot in front of a luxury boutique with warm chandeliers, {BRUNETTE} holding books on the left, {MAN} on the right, {BLONDE} in a black leather trench coat walking out with a white shopping bag, pedestrians passing",
          "the blonde walks out, calls his name, he offers his arm; pedestrians cross in front of the lens", f"wide shot in front of a miniature boutique, {A_BLONDE} in a black leather trench coat walks out with a shopping bag, {A_MAN} offers his arm"),
        S(16.2, 20.2, "OTS 뒷모습", "여자 뒤", "고정", "0,1,2,4,5", "전경 여자 머리, 원경 남자가 금발 허리를 감싸고 떠남", "커플이 걸어감, 그녀가 바라봄", "—", "하드컷", "—", "Seedance",
          f"over-the-shoulder from {BRUNETTE}, {MAN} walking away with his arm around the blonde down a snowy street", "the couple walks away; she turns her head to watch", f"over-the-shoulder from {A_BRUN}, {A_MAN} walking away arm-in-arm with {A_BLONDE}"),
        S(20.2, 25.0, "CU + 명함", "정면", "고정", "1,4,7", "얼굴 상단, 하단에 명함이 올라옴", "책 사이 명함 발견 → 읽고 눈을 굴림", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {BRUNETTE} looking down then lifting a white business card into frame at the bottom", "she finds a business card between the books, reads it, rolls her eyes", f"close-up of {A_BRUN} lifting a tiny business card into frame"),
        S(25.0, 27.0, "WS 뒷모습", "뒤", "고정", "1,4,7", "초록 쓰레기통 전경, 여자 뒷모습, 원경 커플", "명함을 쓰레기통에 던지고 걸어감", "—", "엔딩", "종이 툭",
          "Kling", f"wide shot from behind, {BRUNETTE} flicking a business card into a green city trash can and walking away down the snowy avenue, the couple far ahead",
          "she tosses the card into the bin and walks away", f"wide shot from behind, {A_BRUN} tossing a tiny card into a green trash can and walking away"),
        S(27.0, 27.24, "꼬리", "—", "—", "4", "마지막 프레임", "—", "—", "끝", "—", "편집", "", "", ""),
    ],
    "cast": DF_CAST, "rotate": False,
}

COAT = "a woman with big voluminous 1990s golden-blonde hair, gold hoop earrings and a long cream wool coat"
GENT = "a tall man with slicked dark hair in a long navy overcoat over a white open-collar shirt"
A_COAT = "a golden long-haired {ANIMAL} lady in a long cream wool coat and hoop earrings"
A_GENT = "a dark-furred {ANIMAL} gentleman in a long navy overcoat and white shirt"

PAGE_GENT = {
    "key": "gent", "file": None, "rank": "dreamfall 링크 ⑤",
    "title": "The Gentleman — 흙탕물 맞은 코트, 새 코트를 사 주는 남자",
    "url": "https://www.instagram.com/dreamfall.art/reel/Dc6u2B2uN3C/",
    "metrics": "좋아요 1.1M · 댓글 6.2K · 공유 33.4K · 2026-09-06 업로드 (연령 제한 콘텐츠)",
    "spec": "32.1초 · 원본 720×1280 제공본 기준 · 컷 약 29개 · 평균 샷 1.1초 (초반 2.7~6.3s 0.2~0.6초 급속 몽타주)",
    "music": "Piero Piccioni — 'Lady Love' (인스타 음원 표기, 60~70년대 이탈리아 영화음악 라운지 재즈). 대사 전사 불가",
    "tool": "Made in @syntx_global (Seedance 포함 멀티모델 플랫폼, 캡션 명시) · 'CODE' 댓글 → 제휴 할인 링크",
    "hook": "0~1.5초: 택시 유리창에 도시 불빛이 흐르는 얼굴 클로즈업 — 뮤직비디오 같은 첫 장면, 공유 3.3만",
    "formula": [
        "① 0~4s 택시 → 하차 (유리 반사, 0.3초 급속 컷)",
        "② 4~7.4s 사고: 차가 물웅덩이를 튀김 → 흰 코트에 흙탕물 → 기막힌 표정",
        "③ 7.4~12.7s 리무진에서 내린 남자가 다가와 말을 검",
        "④ 12.7~27.6s 그녀를 이끌고 부티크로, 그녀는 밖에서 기다림",
        "⑤ 27.6~32.1s 유리창 너머 새 코트를 고르는 남자 → 그녀의 미소, 보케 (완결형 엔딩)",
    ],
    "why": [
        "공유 3.3만 = '나도 이런 남자' 판타지를 친구에게 보내는 공유형 콘텐츠",
        "시리즈 없이 한 편으로 완결 → 누구나 이해",
        "나쁜 일(흙탕물) → 구원(새 코트)의 감정 반전",
        "라운지 재즈 음악 + 90년대 룩 = 광고처럼 고급스러움",
    ],
    "techniques": DF_TECH_COMMON[:4] + [
        ("유리 레이어링 (Glass layering)", "택시 창, 부티크 쇼윈도, 빗방울 유리 — 반사·보케로 한 화면에 층을 겹침. 엔딩 샷의 하트 모양 보케가 감정 포인트"),
        ("스타카토 몽타주 (Staccato montage)", "2.7~4.0s 0.2~0.3초 컷 5개로 택시 하차를 쪼갬 → 음악 박자에 맞춘 리듬 편집"),
        ("원인-결과 인서트 (Cause & effect insert)", "물 튀김 와이드 → 얼굴 → 코트 얼룩 인서트 → 얼굴: 4컷으로 '사고'를 설명"),
        ("매치 온 액션 (Match on action)", "택시 문을 여는 동작을 여러 각도로 이어 붙여 움직임이 끊기지 않게"),
    ],
    "shots": [
        S(0.0, 1.53, "CU (유리 너머)", "측면", "고정 + 반사 흐름", "1,2,4,5,7,8", "택시 창 유리 너머 얼굴, 도시 불빛·네온 반사가 얼굴 위로 흐름",
          "창밖을 보며 생각에 잠김", "—", "하드컷", "택시 안 앰비언스, 음악 시작", "Veo / Seedance (유리 반사)",
          f"close-up through a taxi window of {COAT}, city lights and red neon reflections sliding across the glass over her face, rain specks",
          "reflections of passing lights glide over her face, she gazes out", f"close-up through a taxi window of {A_COAT}, city light reflections sliding over the glass"),
        S(1.53, 2.73, "MS (택시 안)", "창밖에서", "고정", "0,1,3,4", "택시 뒷좌석, 창틀 안 그녀", "손가락으로 코끝을 만지며 딴 생각", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"medium shot through the open rear window of a yellow cab, {COAT} touching her nose absentmindedly", "she touches her nose, thinking", f"medium shot through a taxi window, {A_COAT} touching its nose"),
        S(2.73, 4.03, "스타카토 몽타주", "다양", "0.2~0.5초 컷 ×4", "1,4,7", "택시 문 테두리, 흩날리는 머리, 문 손잡이의 손", "택시에서 내리는 동작을 쪼갠 컷들", "—", "점프컷 몽타주", "문 여닫힘",
          "Kling (동작 조각)", f"fragmented close shots of {COAT} stepping out of a yellow taxi: hair, the door frame, her hand on the yellow door",
          "quick fragments of her getting out of the cab, hair tossing", f"fragmented close shots of {A_COAT} stepping out of a miniature yellow taxi"),
        S(4.03, 4.63, "WS", "눈높이", "고정", "5,8", "오른쪽 그녀 전신, 왼쪽 젖은 도로·택시·스팀·단풍", "인도를 걸어감", "—", "하드컷", "힐 소리",
          "Seedance", f"wide shot of {COAT} walking along a wet Manhattan sidewalk, yellow cabs, steam, fallen autumn leaves", "she walks along the curb", f"wide shot of {A_COAT} walking along a wet miniature Manhattan sidewalk"),
        S(4.63, 5.13, "WS", "눈높이", "고정", "3,4,5,6", "차가 지나가며 물보라가 그녀를 덮침", "물웅덩이 물 튐", "—", "하드컷", "물 촤악!", "Kling (물 시뮬레이션)",
          f"a black sedan speeding past through a puddle, a wave of muddy water splashing onto {COAT}", "the car hits the puddle and splashes her", f"a car splashing a wave of muddy water onto {A_COAT}"),
        S(5.13, 5.73, "CU", "살짝 하이", "고정", "1,4,7", "얼굴, 입 벌림", "충격", "—", "하드컷", "헉", "Hailuo(MiniMax)",
          f"close-up of {COAT} shocked, mouth open, hair wet", "she gasps in shock", f"close-up of {A_COAT} shocked, mouth open"),
        S(5.73, 6.33, "인서트", "정면", "고정", "4,5,7,8", "크림 코트 위 흙탕물 얼룩 흘러내림", "얼룩", "—", "하드컷", "물 뚝뚝", "Kling",
          "insert close-up of a muddy brown stain dripping down a cream wool coat", "mud drips down the fabric", "insert of a muddy stain dripping down a tiny cream coat"),
        S(6.33, 7.43, "CU", "정면", "고정", "1,4,7", "얼굴", "눈을 굴리며 한숨 (기막힘)", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {COAT} rolling her eyes in exasperation", "she rolls her eyes and exhales", f"close-up of {A_COAT} rolling its eyes"),
        S(7.43, 8.83, "WS", "눈높이", "고정", "3,4,5,6,7", "검은 링컨 리무진, 남자가 뒷문에서 내림", "남자가 내려서 다가옴", "—", "하드컷", "차 문",
          "Seedance", f"wide shot, {GENT} stepping out of the back of a black stretch limousine on a wet street", "he steps out and walks toward her", f"wide shot, {A_GENT} stepping out of a black miniature limousine"),
        S(8.83, 9.93, "OTS", "남자 뒤", "고정", "0,1,3,4", "전경 남자 등, 그녀가 얼룩진 코트를 내려다봄", "코트를 털며 속상", "—", "하드컷", "—", "Seedance",
          f"over-the-shoulder behind {GENT}, {COAT} looking down at her stained coat", "she brushes at the stain, upset", f"over-the-shoulder, {A_COAT} looking at its stained coat"),
        S(9.93, 10.63, "CU", "살짝 로우", "고정", "1,4,7", "그녀가 올려다봄", "그를 올려다봄", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {COAT} looking up at someone", "she looks up at him", f"close-up of {A_COAT} looking up"),
        S(10.63, 11.73, "CU", "살짝 하이", "고정", "1,4,7", "남자 얼굴", "말을 건넴", "(대사)", "하드컷", "—", "Veo (립싱크)",
          f"close-up of {GENT} speaking gently", "he says something kind", f"close-up of {A_GENT} speaking"),
        S(11.73, 12.73, "CU", "정면", "고정", "1,4,7", "그녀 눈 감음", "'하…' 한숨", "(대사)", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {COAT} closing her eyes with a sigh", "she closes her eyes and sighs", f"close-up of {A_COAT} sighing"),
        S(12.73, 16.43, "2S 전경 차지붕", "눈높이", "고정", "0,1,2,3,4,5", "하단 1/3 젖은 차 지붕, 위로 두 사람, 스팀", "남자가 그녀를 이끌며 걸음", "—", "하드컷", "—",
          "Seedance", f"two-shot over the wet roof of a black car in the foreground, {GENT} guiding {COAT} along the sidewalk, street steam", "they walk together past the car",
          f"two-shot over a wet car roof, {A_GENT} guiding {A_COAT}"),
        S(16.43, 17.13, "MS", "측면", "고정", "0,1,3,4", "부티크 쇼윈도 앞 두 사람", "가게를 가리킴", "—", "하드컷", "—", "Seedance",
          f"{GENT} and {COAT} in front of a menswear boutique window, he gestures inside", "he gestures toward the shop", f"{A_GENT} and {A_COAT} in front of a boutique window"),
        S(17.13, 18.73, "CU", "살짝 하이", "고정", "1,2,4,5", "남자 얼굴, 오른쪽 전경 그녀 머리", "말함", "(대사)", "하드컷", "—", "Veo",
          f"close-up of {GENT} talking to her, her blonde hair in the foreground", "he talks warmly", f"close-up of {A_GENT} talking"),
        S(18.73, 21.53, "CU 보케", "정면", "고정", "1,4,7", "그녀 얼굴, 따뜻한 보케", "숨을 내쉬며 마음이 풀림", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {COAT} with warm bokeh behind, softening", "she exhales and her expression softens", f"close-up of {A_COAT} softening, warm bokeh"),
        S(21.53, 23.43, "CU", "정면", "고정", "1,4,7", "남자 진지", "진심 어린 눈빛", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {GENT}, sincere eyes", "he looks at her sincerely", f"close-up of {A_GENT}, sincere"),
        S(23.43, 25.13, "MS", "눈높이", "고정", "1,2,4,5", "부티크 입구, 두 사람", "문을 열어 줌", "—", "하드컷", "문 종", "Seedance",
          f"medium shot at a boutique entrance, {GENT} holding the door for {COAT}", "he opens the door for her", f"{A_GENT} holding a door open for {A_COAT}"),
        S(25.13, 26.63, "유리 너머", "밖에서 안", "고정", "1,4,7", "빗물 흐르는 유리, 가게 안 남자 뒷모습", "남자가 가게 안으로", "—", "하드컷", "빗소리", "Veo (빗방울 유리)",
          f"through rain-streaked shop glass, {GENT} seen from behind inside a warmly lit boutique", "he walks into the shop, rain trickles down the glass", f"through rain-streaked glass, {A_GENT} inside a boutique"),
        S(26.63, 27.63, "MWS", "눈높이", "고정", "0,3,4,6,7", "쇼윈도 옆에서 팔짱 끼고 기다림, 수트 마네킹", "밖에서 기다림", "—", "하드컷", "—", "Seedance",
          f"{COAT} waiting outside a boutique window with suited mannequins, arms crossed", "she waits, arms crossed", f"{A_COAT} waiting outside a boutique window"),
        S(27.63, 29.33, "유리 너머", "밖에서 안", "고정", "1,2,4,5", "빗방울 유리 너머 코트 랙 앞 남자", "새 코트를 고름", "—", "하드컷", "—", "Veo",
          f"through rain-speckled glass, {GENT} choosing a cream coat from a rack inside the boutique", "he pulls a coat from the rack", f"through rain-speckled glass, {A_GENT} choosing a tiny cream coat"),
        S(29.33, 32.13, "CU 보케", "측면→정면", "고정", "1,4,7", "빗방울 유리+하트 모양 보케 너머 그녀 얼굴", "감동한 미소 → 끝", "—", "엔딩", "음악 마무리", "Veo / Hailuo(MiniMax)",
          f"close-up of {COAT} through rain-speckled glass with soft heart-shaped bokeh lights, a touched smile, eyes glistening", "she smiles softly, touched; bokeh drifts",
          f"close-up of {A_COAT} through rain-speckled glass with heart-shaped bokeh, touched smile"),
    ],
    "cast": [("금발 여주인공", "골든 장모 {ANIMAL} + 크림 코트"), ("신사", "짙은 털 {ANIMAL} + 네이비 오버코트"), ("택시·리무진", "미니어처 소품")],
    "rotate": False, "noimg": NOIMG,
}
