# -*- coding: utf-8 -*-
"""dreamfall Part 4 / Episode 3 (restricted reels, analysed in logged-in browser)."""
from data_df import DF_CAST, DF_TECH_COMMON, BRUNETTE, MAN, BLONDE, A_BRUN, A_MAN, A_BLONDE

KEYS = ("t0", "t1", "size", "angle", "move", "grid", "comp", "action", "line", "trans", "sfx", "models", "img", "vid", "ani")


def S(*vals):
    return dict(zip(KEYS, vals))


NOIMG = "브라우저 내부 분석(연령 제한 릴스) — 프레임 파일 저장 불가, 아래 구도 다이어그램으로 대체"

PAGE_DF4 = {
    "key": "df4", "file": None, "rank": "dreamfall 링크 ②",
    "title": "ACROSS THE STREET — PART 4 (카페 대면, 'OUR WEDDING' 청첩장)",
    "url": "https://www.instagram.com/dreamfall.art/reel/DdefXx_tweS/",
    "metrics": "좋아요 1.1M · 댓글 6.6K · 리포스트 26K · 약 4일 전 업로드 (연령 제한 콘텐츠)",
    "spec": "46.5초 · 원본 720×1280 제공본 기준 · 실측 컷 19개 · 평균 샷 2.3초",
    "music": "Mitski — 'My Love Mine All Mine' (인스타 음원 표기). 대사 음성은 로그인 브라우저 분석이라 전사 불가 — 마지막 샷에서 금발이 말하는 입 모양 확인",
    "tool": "캡션: ACROSS THE STREET – PART 4 · 해시태그 #90saesthetic #romance",
    "hook": "0~2초: 금발 라이벌이 뉴욕 인도를 성큼 걸어오는 트래킹 샷 → 2초: 카페 안에서 손잡은 두 사람 뒤로 그녀가 들어옴. '들켰다'는 긴장이 즉시 생김",
    "formula": [
        "① 0~2.9s 침입자 등장 (금발이 카페로 걸어 들어옴, 깊은 초점으로 전경 커플+후경 금발)",
        "② 2.9~14.7s 커플의 달콤한 순간 (미소, 손 겹침 인서트) — 폭풍 전 고요",
        "③ 14.7~24.2s 발견 → 대면 → 주변 손님 수군거림 컷어웨이",
        "④ 25.1~37.8s 두 여자 클로즈업 교차 (시선 대결)",
        "⑤ 37.8s 'OUR WEDDING 10:00 A.M' 카드 인서트 = 반전 폭탄 → 43s 금발의 눈물 대사로 끝",
    ],
    "why": [
        "'삼각관계 대면' — 댓글에서 편 가르기가 일어나는 구조",
        "인서트 한 장('OUR WEDDING')으로 대사 없이 반전을 전달 → 언어 무관",
        "주변 노부부 리액션(21.7s)이 시청자 대신 놀라 줌 = 감정 대리인",
        "마지막 금발 클로즈업에서 동정 여론이 뒤집힘 → 다음 편 대기",
    ],
    "techniques": DF_TECH_COMMON + [
        ("딥 포커스 스테이징 (Deep staging)", "2.1s: 전경 커플, 후경 문으로 들어오는 금발을 한 프레임에. 시청자가 인물보다 먼저 알아챔 = 서스펜스"),
        ("더티 싱글 (Dirty single)", "27s, 39s: 상대 금발 머리를 흐리게 전경에 걸치고 브루넷 클로즈업 → 두 사람이 마주 보고 있다는 공간감"),
        ("리액션 컷어웨이 (Cutaway)", "21.7s 노부부가 차를 마시며 수군댐 → 장면 밖 관객 시선을 화면에 넣음"),
        ("정보 인서트 (Story insert)", "37.8~39.1s 청첩장 클로즈업 1.3초 — 읽을 수 있을 만큼만 보여 줌"),
    ],
    "shots": [
        S(0.0, 2.1, "MCU 트래킹", "정면, 약간 로우", "뒤로 빠지는 트래킹(달리 아웃)", "1,4,7", "금발 얼굴 상단 1/3, 배경 뉴욕 인도·단풍·마천루·젖은 보도",
          "샴페인 새틴 드레스+다이아 목걸이 차림으로 결연하게 걸어옴", "—", "하드컷", "하이힐 소리, 거리 소음", "Seedance / Veo (트래킹 워크)",
          f"medium close-up tracking shot of {BLONDE} in a champagne satin cowl-neck dress walking determinedly down a wet Manhattan sidewalk, autumn trees and skyscrapers behind",
          "she walks toward the camera with a cold determined look, camera dollies backward in front of her", f"tracking shot of {A_BLONDE} in a tiny champagne satin dress walking determinedly down a miniature Manhattan sidewalk"),
        S(2.1, 2.9, "OTS 딥포커스", "커플 뒤", "고정", "0,1,2,4,5", "전경 브루넷 뒷머리+남자 옆얼굴, 손잡은 테이블. 후경 가운데 문으로 금발 입장",
          "커플이 손을 잡고 있고, 뒤로 금발이 카페에 들어옴", "—", "하드컷", "카페 앰비언스, 문 종소리", "Seedance",
          f"over-the-shoulder deep-focus shot in a 1990s Manhattan cafe with wood paneling and lamp shades, {BRUNETTE} in a burgundy dress and {MAN} holding hands at a table, in the background doorway {BLONDE} enters",
          "the couple holds hands; in the background the blonde walks in through the doorway, deep focus", f"deep-focus cafe shot, {A_BRUN} in burgundy and {A_MAN} holding paws at a table, {A_BLONDE} entering in the background"),
        S(2.9, 5.9, "MCU", "살짝 하이", "고정", "1,2,4,5", "브루넷 오른쪽, 뒤로 흰 카페 커튼+놋쇠 봉",
          "눈을 내리깔고 머리끈을 만지며 수줍게 미소", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"medium close-up, {BRUNETTE} in a burgundy long-sleeve square-neck dress, touching her hair tie, eyes down, white cafe curtains on a brass rod behind",
          "she looks down shyly and fiddles with her hair tie, a small smile", f"medium close-up, {A_BRUN} in a burgundy dress fiddling with a hair tie, shy smile, cafe curtains behind"),
        S(5.9, 9.0, "CU", "정면", "고정", "1,4,7", "남자 얼굴 중앙, 따뜻한 텅스텐 배경", "고개 숙이고 환하게 웃음", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {MAN} smiling warmly, looking down, warm cafe light", "he laughs softly, looking down at her hand", f"close-up of {A_MAN} smiling warmly"),
        S(9.0, 10.9, "인서트", "탑-사이드", "고정", "3,4,6,7", "흰 테이블보 위 겹친 손, 뒤로 녹색 테두리 커피잔",
          "남자 손이 그녀 손 위에 겹쳐짐", "—", "하드컷", "—", "Kling / Seedance", "insert close-up of a man's hand resting on a woman's hand on a white tablecloth, a green-rimmed coffee cup blurred behind",
          "his thumb gently strokes her hand", "insert close-up of a golden paw resting on a chocolate-brown paw on a white tablecloth, coffee cup behind"),
        S(10.9, 14.7, "CU", "정면", "고정", "1,4,7", "브루넷 얼굴 중앙, 목걸이 하단", "그를 올려다보며 설레는 눈빛", "—", "하드컷", "—", "Hailuo(MiniMax) / Veo",
          f"close-up of {BRUNETTE} gazing up lovingly, diamond necklace, soft window light", "she gazes at him, lips parting slightly, gentle smile", f"close-up of {A_BRUN} gazing up lovingly, tiny diamond necklace"),
        S(14.7, 16.8, "ECU", "정면", "고정", "1,4", "더 타이트한 얼굴", "눈동자가 옆으로 이동 → 누군가를 발견", "—", "하드컷", "음악 톤 다운", "Hailuo(MiniMax)",
          f"extreme close-up of {BRUNETTE}'s face, eyes shifting to the side", "her eyes shift toward someone approaching, smile fading", f"extreme close-up of {A_BRUN}, eyes shifting sideways, smile fading"),
        S(16.8, 20.0, "WS", "눈높이", "고정", "1,2,4,5,7", "금발이 테이블 옆에 서서 내려다봄, 남자가 올려다봄, 브루넷 뒷모습 전경",
          "금발이 테이블 앞에 멈춰 섬", "—", "하드컷", "—", "Seedance",
          f"wide shot in the cafe, {BLONDE} in a champagne dress standing beside the table holding a clutch, looking down at {MAN} who looks up, brunette's back in the foreground",
          "the blonde stops at the table, the man looks up, frozen", f"wide cafe shot, {A_BLONDE} standing by the table looking down at {A_MAN}"),
        S(20.0, 21.7, "OTS", "남자 뒤", "고정", "3,4,5", "전경 남자 뒷머리, 브루넷이 금발을 올려다봄", "브루넷 당황", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"over-the-shoulder past {MAN}'s head, {BRUNETTE} looking up confused", "she looks up at the newcomer, confused", f"over-the-shoulder, {A_BRUN} looking up confused"),
        S(21.7, 23.2, "MS 컷어웨이", "눈높이", "고정", "1,2,4,5", "노부부가 옆 테이블에서 찻잔을 들고 수군", "여자는 차를 마시고 남자는 귓속말", "—", "하드컷", "찻잔 달그락", "Seedance / Kling",
          "medium shot of an elderly couple at a neighboring cafe table, the woman sipping tea, the man leaning to whisper, white curtains behind", "the old man whispers gossip, the woman sips tea with raised eyebrows",
          "medium shot of an elderly grey {ANIMAL} couple at a cafe table gossiping over tea"),
        S(23.2, 24.2, "MCU", "살짝 하이", "고정", "1,4,7", "남자 고개 숙임", "죄책감에 시선 회피", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"{MAN} looking down guiltily", "he lowers his gaze, jaw tight", f"{A_MAN} looking down guiltily"),
        S(24.2, 25.1, "WS", "눈높이", "고정", "1,2,4,5,7,8", "3인 삼각 구도: 서 있는 금발, 앉은 남자, 등진 브루넷", "정적", "—", "하드컷", "—", "Seedance",
          f"wide three-person composition in the cafe: {BLONDE} standing, {MAN} seated looking up, a brunette with her back to camera, coffee cups on a round white table",
          "tense stillness, only small movements", "wide three-character composition of the angora rival standing, the golden gentleman seated, the brown heroine from behind"),
        S(25.1, 26.9, "CU", "살짝 로우", "고정", "1,4,7", "금발 얼굴, 다이아 목걸이", "경멸 섞인 눈빛", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {BLONDE}, cold disdainful stare, diamond necklace", "she stares down coldly", f"close-up of {A_BLONDE}, cold stare"),
        S(26.9, 28.5, "CU 더티싱글", "정면", "고정", "0,1,3,4", "오른쪽 전경 흐린 금발 머리, 브루넷 얼굴", "도발적인 눈빛, 입술 삐죽", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {BRUNETTE} with blurred blonde hair in the right foreground, defiant look", "she looks back defiantly, chin raised", f"close-up of {A_BRUN} with blurred cream fur in the foreground, defiant"),
        S(28.5, 30.4, "CU", "정면", "고정", "1,4,7", "금발", "입을 벌려 말함", "(대사)", "하드컷", "—", "Veo (립싱크)",
          f"close-up of {BLONDE} speaking", "she speaks sharply", f"close-up of {A_BLONDE} speaking sharply"),
        S(30.4, 34.6, "WS", "눈높이", "고정", "1,2,4,5,7", "남자가 일어나 금발 쪽으로 몸을 돌림, 브루넷 전경", "남자가 일어섬", "—", "하드컷", "의자 끄는 소리", "Seedance",
          f"wide shot, {MAN} stands up and turns toward {BLONDE}, a brunette seated in the foreground", "he stands up and turns to her", f"wide shot, {A_MAN} stands up and turns toward {A_BLONDE}"),
        S(34.6, 37.8, "MS", "눈높이", "고정", "1,2,4,5,7,8", "금발이 클러치에서 카드를 꺼냄, 전경 브루넷 어깨", "클러치에서 봉투를 꺼냄", "—", "하드컷", "클러치 여닫는 소리", "Kling (손 동작)",
          f"medium shot, {BLONDE} pulling a white card out of a cream clutch beside the cafe table", "she pulls out a card from her clutch", f"medium shot, {A_BLONDE} pulling a card out of a tiny clutch"),
        S(37.8, 39.1, "인서트", "탑", "고정", "1,4,7", "흰 카드 'OUR WEDDING 10:00 A.M', 손가락 하단", "카드를 테이블에 내려놓음", "(텍스트) OUR WEDDING 10:00 A.M", "하드컷", "종이 스치는 소리",
          "Seedance / 이미지+텍스트 합성", "insert close-up of an elegant white card printed 'OUR WEDDING 10:00 A.M' in serif letters, manicured fingers holding it",
          "the card is placed on the table", "insert close-up of an elegant white card printed 'OUR WEDDING 10:00 A.M', a tiny cream paw holding it"),
        S(39.1, 43.0, "CU 더티싱글", "정면", "고정", "0,1,3,4", "브루넷 얼굴, 오른쪽 전경 흐린 금발", "충격으로 입이 벌어짐", "—", "하드컷", "음악 공백", "Hailuo(MiniMax)",
          f"close-up of {BRUNETTE} in shock, lips parted, blurred blonde hair in foreground", "her face drops in shock", f"close-up of {A_BRUN} in shock, blurred cream fur in the foreground"),
        S(43.0, 46.5, "CU", "정면", "고정", "1,4,7", "금발 얼굴, 짙은 나무 배경", "눈물이 고인 채 말함 → 끝", "(대사)", "엔딩", "음악 복귀", "Veo (립싱크) / Hailuo",
          f"close-up of {BLONDE} with teary eyes speaking softly, dark wood paneling behind", "tears in her eyes, she speaks quietly and trembles", f"close-up of {A_BLONDE} with teary eyes speaking softly"),
    ],
    "cast": DF_CAST, "rotate": False, "noimg": NOIMG,
}

PAGE_DF3 = {
    "key": "df3", "file": None, "rank": "dreamfall 링크 ③",
    "title": "ACROSS THE STREET — Episode 3 (옷 입기 몽타주 → 길을 건너 달려온 남자 → 친구의 전화)",
    "url": "https://www.instagram.com/dreamfall.art/reel/DdG7TXrIaOV/",
    "metrics": "좋아요 402.9K · 댓글 3K · 공유 7.3K · 2026-09-10 업로드 (연령 제한 콘텐츠)",
    "spec": "46.2초 · 원본 720×1280 제공본 기준 · 강한 컷 18개 + 옷 입기 구간 빠른 점프컷 · 평균 샷 약 2.3초",
    "music": "Mitski — 'My Love Mine All Mine' (인스타 음원 표기). 대사 전사 불가(브라우저 분석)",
    "tool": "Made in @higgsfield.ai (캡션 명시)",
    "hook": "0초: 센트럴파크가 보이는 방에서 수건 차림으로 버건디 드레스를 들고 고민 = '데이트 준비' 즉시 인식",
    "formula": [
        "① 0~12.5s 준비 몽타주 (수건 → 드레스 → 머리 올림 → 주얼리 뷰티샷)",
        "② 12.5~19s 전신 공개 + 교차편집: 다른 방의 금발(복선)",
        "③ 19~31.6s 호텔 앞: 길 건너 남자가 택시를 지나 달려옴 → 설렘",
        "④ 31.6~41.3s 길 건너 친구가 벽돌폰으로 몰래 보고 통화 (10초 롱테이크)",
        "⑤ 41.3~46.2s 전화 받는 금발 → 복도 → 문이 닫히며 암전 = 4화로",
    ],
    "why": [
        "'준비 몽타주'는 릴스에서 검증된 포맷(GRWM)을 영화 톤으로 바꾼 것",
        "댓글 반응 핵심: '남자가 길을 건너 달려왔다' — 로맨틱 판타지 제공",
        "새 캐릭터(동양인 친구) 투입 = 시리즈 세계관 확장, 댓글 토론 유발",
        "문 닫힘 암전 = 확실한 에피소드 엔딩",
    ],
    "techniques": DF_TECH_COMMON + [
        ("몽타주 점프컷 (Getting-ready montage)", "4.3~8.2s 소매·반지·목선을 0.3~1.4초 단위로 잘게 이어 붙임. 핸드헬드 디테일 샷"),
        ("교차 편집 (Cross-cutting)", "15.1s 다른 공간의 금발을 끼워 넣어 복선. 같은 시간 다른 장소"),
        ("전경 관찰자 롱테이크 (Observer foreground)", "31.6~41.3s 친구 옆얼굴 전경 + 원경 커플, 랙 포커스로 두 층을 오감"),
        ("문 닫힘 암전 (Door wipe to black)", "45.5~46.2s 문이 화면을 덮으며 검은 화면 = 자연스러운 와이프 전환"),
    ],
    "shots": [
        S(0.0, 2.2, "MS", "눈높이", "매우 느린 푸시인", "0,3,4,6,7", "인물 좌측, 오른쪽 옷걸이에 걸린 버건디 드레스, 뒤로 창밖 센트럴파크",
          "흰 수건 차림으로 드레스를 들어 보며 고민", "—", "하드컷", "방 룸톤, 새소리", "Veo / Seedance",
          f"medium shot, {BRUNETTE} wrapped in a white towel holding up a burgundy long-sleeve dress on a hanger, gilded wall sconces, window with Central Park autumn and skyline behind",
          "she holds the dress up, considering it, slow push-in", f"medium shot, {A_BRUN} wrapped in a tiny towel holding up a tiny burgundy dress on a hanger, Central Park view"),
        S(2.2, 2.7, "인서트 (발)", "로우", "고정", "6,7", "맨발과 수건 끝단, 햇빛 드는 카펫", "발걸음", "—", "하드컷", "—", "Kling",
          "low insert of bare feet on a sunlit cream carpet, hem of a white towel", "she steps forward", "low insert of tiny {ANIMAL} paws on a sunlit carpet, towel hem"),
        S(2.7, 4.3, "인서트 (다리)", "로우", "고정", "4,7", "수건이 발목으로 떨어져 쌓임 (다리만)", "수건 드롭 — 암시만, 노출 없음", "—", "하드컷", "천 떨어지는 소리", "Kling",
          "low shot of legs only, a white towel dropping and pooling around the ankles on a carpet, tasteful", "the towel falls to the floor", "a tiny white towel dropping to the floor around tiny {ANIMAL} paws (cute, wholesome)"),
        S(4.3, 8.2, "ECU 몽타주", "다양", "핸드헬드 디테일, 점프컷 4~5개", "3,4,5", "소매를 당김 → 반지 → 드레스 목선 → 눈 내린 얼굴",
          "드레스를 입는 디테일 컷 연속", "—", "점프컷 몽타주", "원단 스치는 소리", "Kling / Seedance (디테일)",
          f"series of extreme close-ups of {BRUNETTE} putting on a burgundy stretch dress: pulling a sleeve, a diamond ring, adjusting the neckline",
          "quick detail moments of dressing, handheld, shallow focus", f"extreme close-ups of {A_BRUN} putting on a tiny burgundy dress: pulling a sleeve, a tiny ring"),
        S(8.2, 10.8, "MS (거울)", "어깨 뒤", "고정", "1,2,4,5", "앞쪽 뒷모습, 금빛 거울에 비친 얼굴", "머리를 올려 묶음", "—", "하드컷", "—", "Seedance",
          f"{BRUNETTE} in a burgundy dress pinning up her hair in front of an ornate gilded mirror, her reflection visible", "she lifts her hair into an updo, looking at the mirror", f"{A_BRUN} in a burgundy dress styling its fur in front of a gilded mirror"),
        S(10.8, 12.5, "CU 뷰티샷", "정면", "고정", "1,4,7", "얼굴 중앙, 드롭 귀걸이+다이아 목걸이", "카메라를 향해 은근한 시선", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"beauty close-up of {BRUNETTE} with an updo, diamond drop earrings and a diamond necklace", "she turns her gaze to the lens slowly", f"beauty close-up of {A_BRUN} with diamond drop earrings and necklace"),
        S(12.5, 15.1, "MWS 전신", "눈높이", "고정", "1,4,7", "창가에 선 전신, 뒤로 맨해튼", "완성된 룩 공개, 서서 기다림", "—", "하드컷", "—", "Veo",
          f"full-length shot of {BRUNETTE} in a fitted burgundy square-neck dress standing by an arched window with the Manhattan skyline", "she stands and exhales, ready", f"full-length shot of {A_BRUN} in a fitted burgundy dress by an arched window"),
        S(15.1, 19.1, "MS 교차편집", "눈높이", "고정", "0,1,3,4", "금발이 다른 아파트 문 앞, 뒤로 남자가 나가는 모습", "금발이 의미심장하게 미소", "—", "하드컷", "문 닫힘", "Hailuo(MiniMax)",
          f"medium shot of {BLONDE} in a champagne satin dress in an elegant apartment hallway, knowing smile, a man in a suit leaving through a door behind her",
          "she smiles knowingly as the man leaves", f"medium shot of {A_BLONDE} in a champagne dress with a knowing smile, the gentleman leaving behind"),
        S(19.1, 21.7, "POV/OTS", "택시 뒤", "고정", "1,4,7", "전경 남자 어깨+노란 택시, 원경 호텔 캐노피 아래 그녀", "그녀가 호텔 입구에서 나옴", "—", "하드컷", "택시·거리 소음", "Seedance",
          f"over-the-shoulder from behind {MAN} and a yellow taxi, across the street {BRUNETTE} in a burgundy dress stepping out under a hotel awning",
          "she walks out from the hotel entrance", f"over-the-shoulder behind {A_MAN} and a miniature yellow taxi, {A_BRUN} stepping out under a hotel awning"),
        S(21.7, 23.7, "MCU", "정면", "고정", "1,4,7", "남자 얼굴, 배경 거리 보케", "그녀를 보고 활짝 웃음", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"medium close-up of {MAN} on the street smiling broadly, bokeh background", "he sees her and smiles", f"medium close-up of {A_MAN} smiling broadly on the street"),
        S(23.7, 25.7, "OTS", "그녀 뒤", "고정", "1,2,4,5", "전경 그녀 뒷머리, 원경 남자가 길을 가로질러 뛰어옴(낙엽)", "남자가 길을 건너 달려옴", "—", "하드컷", "뛰는 발소리", "Kling (달리기)",
          f"over-the-shoulder past {BRUNETTE}'s updo, {MAN} jogging across a leaf-strewn street toward her", "he runs across the street toward her", f"over-the-shoulder past {A_BRUN}, {A_MAN} jogging across a leaf-strewn street"),
        S(25.7, 27.9, "CU", "정면", "고정", "1,4,7", "그녀 얼굴", "고개 숙이며 수줍게 미소", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {BRUNETTE} smiling shyly, looking down", "she smiles and looks down", f"close-up of {A_BRUN} smiling shyly"),
        S(27.9, 28.9, "CU", "정면", "고정", "1,4,7", "남자", "숨을 고르며 말함", "(대사)", "하드컷", "—", "Veo (립싱크)",
          f"close-up of {MAN} slightly out of breath, speaking", "he speaks warmly, catching his breath", f"close-up of {A_MAN} speaking, out of breath"),
        S(28.9, 31.6, "2S 프로필", "측면", "고정", "0,1,2,3,4,5", "두 사람 옆얼굴이 마주 봄, 가까운 거리", "서로 바라봄", "—", "하드컷", "—", "Seedance",
          f"profile two-shot, {BRUNETTE} and {MAN} facing each other closely on the sidewalk", "they hold each other's gaze", f"profile two-shot, {A_BRUN} and {A_MAN} facing each other closely"),
        S(31.6, 41.3, "롱테이크 관찰자", "친구 뒤·옆", "느린 푸시인 + 랙포커스", "0,3,4,6,7", "왼쪽 전경 친구 옆얼굴+벽돌폰, 원경 커플",
          "친구가 벽돌폰으로 통화하며 커플을 지켜봄 (새 캐릭터)", "(통화 대사)", "하드컷", "거리 앰비언스", "Veo (전경+원경 초점 이동) / Seedance",
          "foreground profile of an Asian woman with a sleek black bob and gold earrings in an olive blazer holding a 1990s brick cellphone, across the street a couple talking under a hotel awning, rack focus",
          "she watches the couple while talking on the phone; focus racks from the couple to her face", "foreground profile of a dwarf {ANIMAL} friend in an olive blazer holding a tiny brick cellphone, watching a couple across the street"),
        S(41.3, 44.2, "CU", "정면", "고정", "1,4,7", "금발 얼굴, 흰 유선 수화기", "전화를 받고 표정이 굳음", "—", "하드컷", "—", "Hailuo(MiniMax)",
          f"close-up of {BLONDE} holding a white landline handset, expression hardening", "she listens and her face hardens", f"close-up of {A_BLONDE} holding a landline handset, expression hardening"),
        S(44.2, 45.5, "MS", "문틈", "고정", "1,4,7", "금박 복도, 거울, 금발이 클러치를 들고 걸어옴", "걸어 나감", "—", "하드컷", "힐 소리", "Seedance",
          f"medium shot through a doorway, {BLONDE} in champagne satin walking down an ornate gilded hallway with a mirror and sconces, holding a clutch",
          "she walks toward the door", f"{A_BLONDE} walking down an ornate gilded hallway holding a tiny clutch"),
        S(45.5, 46.2, "와이프", "—", "문이 화면을 덮음", "0,1,2,3,4,5,6,7,8", "짙은 나무 문이 닫히며 검은 화면", "문 닫힘 → 암전", "—", "문 와이프 → 블랙", "문 쾅", "편집",
          "dark wooden door closing toward the camera", "the door swings shut, filling the frame to black", "dark wooden door closing to black"),
    ],
    "cast": DF_CAST, "rotate": False, "noimg": NOIMG,
}
