# -*- coding: utf-8 -*-
"""sickmanai TOP 1~3 shot data (measured cuts from frame-diff analysis)."""

SM_STYLE = ("photorealistic, shot on a smartphone front camera, 9:16 vertical, overcast diffuse daylight, "
            "misty Scottish highland moor, wet green tussock grass, low fog, desaturated greens, "
            "documentary realism, natural handheld micro-shake, no text, no watermark")
SM_ANI_STYLE = ("photorealistic tiny {ANIMAL} in miniature handmade plate armor, real fur detail, "
                "9:16 vertical, overcast diffuse daylight, misty highland moor, documentary realism")

KNIGHT = ("a tiny fluffy cream-golden British shorthair kitten with huge dark round eyes and a pink satin bow on the left ear, "
          "wearing full polished steel plate armor with an engraved fleur-de-lis breastplate, chainmail sleeves, "
          "a short sword on the belt and an ivory linen cape")
ANI_KNIGHT = ("a tiny fluffy {ANIMAL} with a pink satin bow on one ear, wearing full polished steel plate armor "
              "with an engraved fleur-de-lis breastplate, chainmail sleeves, a short sword and an ivory linen cape")
DRAGON = "a colossal crimson-red dragon with ridged horns, spiked brow plates, leathery bat wings and wet scaled skin"

PAGE_SM1 = {
    "key": "sm1", "file": "sm1_DcO8W4rprTp", "rank": "sickmanai 조회수 1위",
    "title": "기사 아기고양이 셀카 → 폰 떨어짐 → 드래곤 등장 (🐱⚔🐉)",
    "url": "https://www.instagram.com/sickmanai/reel/DcO8W4rprTp/",
    "metrics": "조회 4.5M · 좋아요 334,531 · 댓글 3,438 · 2026-08-19 업로드",
    "spec": "15.25초 · 1080×1920 · 30fps · 실측 컷 1개(5.4s) + 카메라 낙하 인카메라 전환",
    "music": "BGM+SFX (가사 없음, Whisper 음성 미검출). 3.5s 컵 던짐 효과음 피크(-12.7dB), 5.6~6.4s 낙하 충돌음 연타, 13.1s 드래곤 포효 후 끝까지 -11dB 유지",
    "tool": "제작자: Higgsfield Creative Partner (캡션: Inspired by @kaye.creatives & @brshdsk, 'prompt' 댓글 유도)",
    "hook": "0초부터 '기사 갑옷 입은 아기고양이가 셀카로 밀크티 마시는' 비현실 조합. 첫 프레임에서 이미 스크롤이 멈춤",
    "formula": [
        "① 0~3.6s 일상 셀카 (귀여움 + 평화) → 시청자 긴장 0",
        "② 3.6s 컵 휙 던짐 = '뭔가 온다' 신호 (행동으로 복선)",
        "③ 5.4s 폰이 풀밭에 떨어지며 화면 90° 회전 = 편집 없는 전환(인카메라 트랜지션)",
        "④ 7.2s~ 누워있는 폰 시점: 작은 고양이 vs 거대 드래곤 — 스케일 대비가 곧 펀치라인",
        "⑤ 13s 드래곤 입 벌림에서 뚝 끝 → 결말 궁금 → pt.2(3위 영상)로 연결 + 반복재생",
    ],
    "why": [
        "크기 대비(스케일 갭): 손바닥만 한 고양이 vs 화면을 채우는 드래곤. 썸네일 한 장으로 설명 끝",
        "POV 파운드푸티지: '진짜 폰으로 찍힌 것 같은' 셀카 → 떨어진 폰. AI 티를 오히려 현실감으로 덮음",
        "15초 짧은 길이 + 클리프행어 엔딩 → 완주율·재시청률 극대화",
        "대사 0, 자막 0 → 언어 장벽 없음 = 글로벌 확산",
    ],
    "techniques": [
        ("인카메라 트랜지션 (In-camera transition)", "컷 대신 '폰이 떨어지는 움직임' 자체로 장면을 바꿈. 5.4~7.2s 풀잎이 화면을 쓸고 지나가는 모션블러가 사실상 와이프 전환 역할"),
        ("더치 90° (Dutch angle 90°)", "땅에 누운 폰 시점. 16:9로 정상 생성한 영상을 FFmpeg transpose=1(시계방향 90°)로 돌려 9:16을 채움 → 제작 핵심 트릭"),
        ("셀카 POV + 전경 팔 (Foreground arm)", "왼쪽 하단 갑옷 팔이 화면을 가려 '들고 찍는' 증거가 됨. 광각 왜곡으로 얼굴 크게"),
        ("스케일 리빌 (Scale reveal)", "처음엔 고양이만 보여 주고, 전환 후에 드래곤 전체를 공개"),
        ("하드 엔딩 / 루프 (Hard out)", "포효 정점에서 페이드 없이 끊음 → 자동 반복 시 처음 셀카로 돌아가 대비 효과 재발생"),
    ],
    "shots": [
        {"t0": 0.0, "t1": 3.6, "size": "MCU 셀카", "angle": "눈높이, 광각 셀카", "move": "핸드헬드 미세 흔들림", "grid": "0,1,3,4,6",
         "comp": "고양이 머리 화면 상단 1/3, 중앙~좌측. 좌하단 전경에 갑옷 팔(카메라 든 팔). 우측 앞발에 밀크티 컵",
         "action": "빨대로 아이스 밀크티를 쪽쪽 마시며 카메라를 봄. 눈 깜빡임 1회",
         "line": "없음", "trans": "연속 (컷 없음)", "sfx": "바람 소리, 빨대 흡입음, 멀리서 낮은 웅웅 소리(드래곤 복선)",
         "models": "Kling (셀카 손떨림·빨대 입 모양) / Seedance (캐릭터 일관성)",
         "img": f"selfie-style front camera photo of {KNIGHT}, holding a clear plastic cup of iced milk tea with a dome lid and a white straw in its right paw, sipping through the straw, its armored left arm extends toward the lens in the bottom-left foreground as if holding the phone, wide-angle selfie distortion, head in the upper third",
         "vid": "the kitten sips the milk tea through the straw twice, blinks once, looks into the lens; subtle handheld selfie shake; fog drifts slowly behind; grass sways in light wind",
         "ani": f"selfie-style front camera photo of {ANI_KNIGHT}, holding a clear cup of iced milk tea with a straw, sipping, armored arm in the bottom-left foreground holding the phone, wide-angle selfie distortion"},
        {"t0": 3.6, "t1": 5.4, "size": "MCU 셀카", "angle": "눈높이", "move": "핸드헬드, 몸 돌리며 흔들림 증가", "grid": "0,1,3,4",
         "comp": "컵이 우상단 프레임 밖으로 날아감(3.75s). 고양이 몸이 오른쪽으로 틀어짐",
         "action": "컵을 어깨 너머로 휙 던짐(내용물 튐) → 앞발로 카메라 쪽 제스처 → 무언가를 느끼고 옆을 봄",
         "line": "없음", "trans": "연속 → 5.4s 폰 낙하 시작", "sfx": "컵 휙 + 액체 튀는 소리(3.5s 피크), 갑옷 철컥",
         "models": "Kling (물체 투척 물리) / Seedance",
         "img": f"same selfie framing, {KNIGHT} tossing the milk tea cup over its shoulder, the cup flying out of frame at the top right with milk splashing, paw raised",
         "vid": "the kitten flings the cup over its shoulder, milk tea splashes through the air, then it raises a paw toward the lens and turns its head sharply to the right as if hearing something huge; handheld shake increases",
         "ani": f"same selfie framing, {ANI_KNIGHT} tossing its milk tea cup over its shoulder, milk splashing, paw raised, head turning sharply"},
        {"t0": 5.4, "t1": 7.2, "size": "전환(모션블러)", "angle": "회전하며 추락", "move": "폰 낙하·회전 90°, 강한 모션블러", "grid": "0,1,2,3,4,5,6,7,8",
         "comp": "풀잎이 화면 전체를 쓸고 지나감. 끝에 화면이 90° 누운 상태로 정착",
         "action": "폰이 손에서 떨어져 풀밭에 옆으로 떨어짐. 흔들림이 잦아들며 드래곤 머리가 보이기 시작",
         "line": "없음", "trans": "인카메라 휩/낙하 전환 (컷 대신)", "sfx": "휘익 + 풀밭 '퍽' 착지음 2~3회(5.6/6.0/6.35s 온셋)",
         "models": "Kling (카메라 낙하 물리) / 또는 FFmpeg 합성(아래 레시피)",
         "img": "extreme close-up of wet green grass blades rushing past the lens, heavy motion blur, a blurred red shape in the background",
         "vid": "the phone camera tumbles from the paw and falls onto the grass, rotating, heavy motion blur, grass blades sweep across the lens, it lands on its side and settles",
         "ani": "extreme close-up of wet grass blades rushing past the lens, heavy motion blur, camera tumbling onto the ground"},
        {"t0": 7.2, "t1": 13.0, "size": "WS (누운 폰 고정)", "angle": "지면 높이, 90° 회전", "move": "고정(락오프)", "grid": "0,3,6,1,4,7",
         "comp": "원본 16:9 기준: 왼쪽 아래 작은 고양이(프레임 높이의 1/5), 오른쪽 화면 60% 드래곤 머리. 90° 돌려 9:16에 배치",
         "action": "드래곤이 콧김을 뿜으며 고양이를 내려다봄 → 고양이가 9.7s 칼을 뽑아 겨눔",
         "line": "없음", "trans": "연속", "sfx": "드래곤 낮은 으르렁, 콧김, 칼 뽑는 쇳소리(9.4~9.85s)",
         "models": "Seedance / Veo (큰 생물 스케일·안개) — 16:9로 생성 후 회전",
         "img": f"ground-level locked-off shot from a phone lying in the grass, 16:9 landscape, on the left a tiny {KNIGHT} standing and facing right, on the right {DRAGON} lowering its enormous head toward the kitten, thick fog, overcast",
         "vid": "the dragon breathes heavily, nostrils flaring, slowly lowers its head; the tiny kitten draws its short sword and points it at the dragon; camera completely still, lying on the ground",
         "ani": f"ground-level locked-off shot from a phone lying in the grass, 16:9, on the left a tiny {ANI_KNIGHT} facing right, on the right {DRAGON} lowering its enormous head, thick fog"},
        {"t0": 13.0, "t1": 15.25, "size": "WS", "angle": "지면 높이, 90° 회전", "move": "고정 → 드래곤이 뒤로 물러나며 스케일 변화", "grid": "1,4,7",
         "comp": "드래곤이 입을 최대로 벌려 화면 중앙을 채움, 고양이는 좌측 작게",
         "action": "드래곤이 입을 벌려 포효(13.25s) → 날개를 펴며 뒤로 물러남 → 컷아웃",
         "line": "없음", "trans": "하드 엔딩 (루프 포인트)", "sfx": "포효(13.1s 피크), 날개 펄럭",
         "models": "Kling / Seedance (입 벌림·날개 전개)",
         "img": f"same ground-level shot, {DRAGON} opening its jaws wide in a roar toward the tiny armored kitten holding up its sword, wings spreading, fog",
         "vid": "the dragon opens its jaws wide and roars at the kitten, then rears back spreading its wings; the kitten holds its ground; camera still",
         "ani": f"same ground-level shot, {DRAGON} roaring with jaws wide toward the tiny armored {{ANIMAL}} raising its sword, wings spreading, fog"},
    ],
    "cast": [("아기고양이 기사", "{ANIMAL} 기사 (핑크 리본 유지 = 시리즈 아이덴티티)"), ("붉은 드래곤", "그대로 유지 (스케일 대비 핵심)")],
    "rotate": True,
}

PAGE_SM2 = {
    "key": "sm2", "file": "sm2_Dbd2A_JJFeZ", "rank": "sickmanai 조회수 2위",
    "title": "이별 후 고양이 (Kitty after heartbreak) — 원테이크 감정 연기",
    "url": "https://www.instagram.com/sickmanai/reel/Dbd2A_JJFeZ/",
    "metrics": "조회 3.8M · 좋아요 262,314 · 댓글 2,675 · 2026-07-31 업로드",
    "spec": "10.03초 · 1440×1080 (4:3 가로) · 23.976fps · 컷 0개 (단일 테이크)",
    "music": "중국어 보컬 발라드 추정 (Whisper가 0~1s 구간에서 '真爱过' 인식). 음량 -15~-19dB로 일정 = 음악만 깔린 구조. 곡명은 확인 못 함",
    "tool": "캡션: 'Kitty after heartbreak #cat #orangecat #ai'",
    "hook": "0초: 주황 고양이가 권총을 카메라에 겨누고 이를 드러냄 = 밈 포맷(고양이+총) 즉시 인식",
    "formula": [
        "① 0~2s 위협 (으르렁, 총구 정면) — 웃긴 밈처럼 시작",
        "② 2~5s 감정 붕괴: 눈에 눈물이 차오르고 아랫입술 떨림",
        "③ 5~6.5s 총을 천천히 내림(프레임 아래로 퇴장) = 포기",
        "④ 6.5~10s 눈 감고 울음 참기 + 느린 푸시인 → 여운 남기고 끝 (자동 반복)",
    ],
    "why": [
        "'웃긴 밈 → 슬픔'으로 뒤집히는 감정 반전이 10초 안에 완결",
        "공감 캡션('이별 후')이 댓글에서 자기 이야기를 꺼내게 만듦 → 댓글·공유 폭증",
        "컷 없는 단일 CU라 AI 생성 1회로 제작 가능 = 제작비 최소",
        "4:3 가로 원본이 오히려 '옛날 영화 한 장면' 느낌을 줌",
    ],
    "techniques": [
        ("원테이크 CU (Single-take close-up)", "편집 없이 연기만으로 감정 곡선을 만듦. 미세 표정 표현이 가장 좋은 모델을 써야 함"),
        ("슬로 푸시인 (Slow push-in)", "6초 이후 얼굴이 약 10% 커짐 = 감정 강조. FFmpeg zoompan으로 후반에 넣어도 됨"),
        ("얕은 심도 배경 (Shallow DOF)", "회색 실내가 완전히 흐림 → 얼굴과 총 두 요소만 남음"),
        ("오브젝트 퇴장 (Prop exit)", "총이 프레임 아래로 빠져나가는 것 = 대사 없이 '포기'를 전달"),
        ("음악 주도 편집 (Music-driven)", "효과음 없이 보컬곡 하나로 감정을 끌고 감"),
    ],
    "shots": [
        {"t0": 0.0, "t1": 2.0, "size": "CU", "angle": "정면, 약간 로우", "move": "고정", "grid": "1,4,5,7,8",
         "comp": "고양이 얼굴 화면 중앙~상단, 오른쪽 하단에 앞발+권총(총구가 카메라를 향함). 배경 흐린 회색 실내",
         "action": "이빨을 드러내며 으르렁/말하듯 입을 움직임, 총을 흔들며 위협",
         "line": "없음 (음악)", "trans": "연속 (단일 테이크)", "sfx": "음악 시작(0.05s 온셋)",
         "models": "Hailuo(MiniMax) (동물 미세 표정) / Kling",
         "img": "cinematic close-up of a chubby orange tabby cat with round amber eyes holding a black pistol in its front paw, aiming at the camera, bared teeth, angry, blurred grey apartment background, shallow depth of field, 4:3",
         "vid": "the cat snarls and mouths words at the camera, shaking the pistol slightly, angry but trembling; camera still",
         "ani": "cinematic close-up of a chubby {ANIMAL} holding a toy water pistol in its paw aimed at the camera, bared teeth, angry, blurred grey apartment background, shallow depth of field, 4:3"},
        {"t0": 2.0, "t1": 5.0, "size": "CU", "angle": "정면", "move": "고정", "grid": "1,4,5,7,8",
         "comp": "동일 구도. 눈동자에 물기 하이라이트가 커짐",
         "action": "입을 다물고 눈에 눈물이 차오름, 아랫입술 떨림, 코를 찡긋",
         "line": "없음", "trans": "연속", "sfx": "보컬 상승",
         "models": "Hailuo(MiniMax) / Veo (눈물·습기 표현)",
         "img": "same close-up, the orange tabby cat's eyes welling up with tears, glossy reflections, lower lip trembling, pistol still raised",
         "vid": "tears slowly well up in the cat's eyes, its lower lip trembles, it sniffs, the pistol wavers; camera still",
         "ani": "same close-up, the {ANIMAL}'s eyes welling up with tears, glossy reflections, lip trembling, toy pistol wavering"},
        {"t0": 5.0, "t1": 6.5, "size": "CU → 살짝 타이트", "angle": "정면", "move": "푸시인 시작", "grid": "1,4,7",
         "comp": "총이 오른쪽 아래로 빠져나감. 얼굴이 화면 중앙에 남음",
         "action": "총을 천천히 내림, 눈물 한 방울",
         "line": "없음", "trans": "연속", "sfx": "4.5s 음악 전환점",
         "models": "Hailuo(MiniMax) / Kling",
         "img": "same close-up, the cat lowering the pistol out of frame, a single tear on its cheek fur, heartbroken",
         "vid": "the cat slowly lowers the pistol out of the bottom of the frame, a tear rolls down, slow push-in begins",
         "ani": "same close-up, the {ANIMAL} lowering the toy pistol out of frame, a single tear on its cheek, heartbroken"},
        {"t0": 6.5, "t1": 10.03, "size": "CU (푸시인 끝)", "angle": "정면", "move": "느린 푸시인 약 +10%", "grid": "1,4,7",
         "comp": "얼굴이 프레임을 가득 채움, 눈이 반쯤 감김",
         "action": "눈을 꼭 감고 울음을 참으며 입을 꽉 다묾 → 끝",
         "line": "없음", "trans": "하드 엔딩 → 루프", "sfx": "9.05s / 9.85s 음악 악센트",
         "models": "Hailuo(MiniMax) / Veo",
         "img": "tight close-up of the orange tabby cat with eyes half closed, holding back tears, lips pressed, melancholic, blurred background",
         "vid": "the cat closes its eyes tightly, holding back a sob, chin trembling; very slow push-in",
         "ani": "tight close-up of the {ANIMAL} with eyes half closed, holding back tears, lips pressed, melancholic"},
    ],
    "single_take": True,
    "cast": [("주황 고양이", "{ANIMAL} (볼살 많은 품종일수록 표정 전달 ↑)"), ("권총", "⚠️ 물총/바나나 등 소품으로 교체 권장 (플랫폼·생성기 정책)")],
    "rotate": False,
}

PAGE_SM3 = {
    "key": "sm3", "file": "sm3_DcUdF_fJ9M_", "rank": "sickmanai 조회수 3위",
    "title": "기사 고양이 pt.2 — 넘어진 카메라 앞에서 드래곤을 길들여 타고 날아감",
    "url": "https://www.instagram.com/sickmanai/reel/DcUdF_fJ9M_/",
    "metrics": "조회 3.6M · 좋아요 370,870 · 댓글 2,312 · 2026-08-21 업로드",
    "spec": "26.0초 · 1080×1920 · 30fps · 실측 컷 5개 (4.6 / 12.3 / 17.4 / 20.1 / 21.8s) · 평균 샷 4.3초",
    "music": "대사 없음. 온셋: 0.25/1.9s 바람, 6.0~7.35s 드래곤 돌진 충돌음 연타, 13.1~15.05s 올라타기, 20.85s 날갯짓, 24.95~25.75s 비행 이륙",
    "tool": "캡션: '🐱⚔🐉 pt.2 Comment guide' — 1위 영상의 속편",
    "hook": "0초: 안개 낀 들판에 칼을 세워 든 작은 기사 고양이, 망토가 바람에 휘날림 = 영화 포스터 같은 첫 장면",
    "formula": [
        "① 0~4.6s 영웅 포즈(정적인 긴장)",
        "② 4.6s 카메라가 쓰러짐 → 90° 누운 시점에서 드래곤 착지·돌진(혼돈)",
        "③ 12.3s 드래곤이 머리를 낮춤 = 적에서 동료로 반전",
        "④ 13~17s 고양이가 드래곤 머리 위로 올라탐",
        "⑤ 17.4~26s 고삐를 쥐고 이륙 → 하늘로 사라짐 (완결 카타르시스)",
    ],
    "why": [
        "1위 영상의 '다음 이야기' = 시리즈 소비 욕구 (pt.1 → pt.2)",
        "공포 → 반전 → 우정 → 비행으로 이어지는 26초짜리 3막 구조",
        "고정된 누운 카메라 앵글 덕분에 AI 클립 5개를 이어도 컷이 거의 안 느껴짐",
        "마지막 하늘 실루엣 = 여운 + 캡처하고 싶은 장면",
    ],
    "techniques": [
        ("락오프 연속 이어붙이기 (Locked-off chaining)", "카메라가 같은 자리에 누워 있으니 각 AI 클립의 마지막 프레임을 다음 클립의 첫 프레임으로 써서 이으면 점프컷이 거의 안 보임"),
        ("더치 90° 트릭", "16:9 가로로 생성 → transpose=1로 90° 회전 → 9:16. 1위 영상과 동일"),
        ("카메라 넘어짐 전환 (Knock-over)", "4.0~4.6s 카메라가 바람/충격에 기울며 넘어짐 = 장면 전환 겸 긴장 폭발"),
        ("화면 밖 공간 활용 (Off-screen space)", "드래곤이 화면 밖에서 들어오고 하늘 쪽 화면 밖으로 사라짐 → 세계가 더 커 보임"),
        ("실루엣 엔딩 (Silhouette out)", "하얀 하늘을 배경으로 한 드래곤 배 쪽 실루엣으로 끝"),
    ],
    "shots": [
        {"t0": 0.0, "t1": 4.6, "size": "WS", "angle": "약간 로우, 정면", "move": "고정 → 4.0s부터 기울며 넘어짐", "grid": "1,4,7",
         "comp": "고양이 중앙, 칼날이 수직으로 머리 위까지. 망토가 화면 왼쪽으로 펄럭. 하단 1/3은 풀밭, 상단은 안개",
         "action": "두 손으로 롱소드를 세워 들고 정면 응시. 바람이 거세지다가 카메라가 기울어짐",
         "line": "없음", "trans": "카메라 넘어짐 (인카메라)", "sfx": "강풍, 망토 펄럭, 풀 쓸림",
         "models": "Veo / Seedance (안개·천 시뮬레이션)",
         "img": f"wide shot, slightly low angle, {KNIGHT} standing in the center of a foggy moor holding a longsword upright with both paws, the blade rising above its head, the ivory cape whipping to the left in strong wind, tall grass swaying, 9:16",
         "vid": "strong wind blows the cape and the grass; the kitten stands still like a hero; at the end the camera tilts and falls over to its side",
         "ani": f"wide shot, slightly low angle, {ANI_KNIGHT} standing in a foggy moor holding a longsword upright, cape whipping in the wind, 9:16"},
        {"t0": 4.6, "t1": 12.3, "size": "WS (누운 카메라)", "angle": "지면, 90° 회전", "move": "고정, 돌진 시 충격 흔들림", "grid": "0,1,3,4,6,7",
         "comp": "원본 16:9: 왼쪽 고양이 작게, 드래곤이 오른쪽에서 착지→돌진. 이끼 낀 바위가 전경 하단",
         "action": "드래곤 착지 → 입 벌리고 돌진(5.75s) → 고양이가 굴러 피함(6.75s) → 흙 튐 → 고양이 바위 옆에서 일어섬 → 드래곤 머리가 가까이 옴",
         "line": "없음", "trans": "하드컷 (같은 앵글)", "sfx": "착지 쿵, 포효, 흙 튀는 소리 연타(6.0~7.35s), 갑옷 구르는 소리",
         "models": "Kling (격한 액션·충돌) / Seedance",
         "img": f"ground-level shot from a camera lying in the grass, 16:9, {DRAGON} landing on the right and lunging with open jaws at a tiny armored kitten knight on the left, dirt spraying, mossy boulder in the foreground, fog",
         "vid": "the dragon lands heavily and lunges with its jaws open, the kitten rolls aside, dirt sprays onto the lens, the kitten gets back up beside the boulder, the dragon's huge head swings closer; camera fixed on the ground with impact shakes",
         "ani": f"ground-level shot from a camera lying in the grass, 16:9, {DRAGON} lunging with open jaws at a tiny armored {{ANIMAL}} knight who rolls aside, dirt spraying, mossy boulder foreground, fog"},
        {"t0": 12.3, "t1": 17.4, "size": "WS", "angle": "지면, 90° 회전", "move": "고정", "grid": "0,1,3,4",
         "comp": "드래곤이 머리를 땅에 낮춤, 고양이가 머리 위(뿔 사이)로 올라감",
         "action": "드래곤이 머리를 숙여 복종 → 고양이가 콧등을 밟고 머리 위로 올라 앉음",
         "line": "없음", "trans": "하드컷 (같은 앵글)", "sfx": "드래곤 낮은 그르렁, 발톱 긁는 소리",
         "models": "Seedance / Kling",
         "img": f"same ground-level rotated framing, {DRAGON} lowering its head to the ground in submission, the tiny armored kitten climbing onto its head between the horns",
         "vid": "the dragon slowly lowers its head, the kitten climbs up its snout and sits between the horns; camera still",
         "ani": f"same ground-level framing, {DRAGON} lowering its head, the tiny armored {{ANIMAL}} climbing onto its head between the horns"},
        {"t0": 17.4, "t1": 20.1, "size": "MWS", "angle": "지면에서 올려다봄", "move": "고정", "grid": "1,4,5,7",
         "comp": "드래곤이 몸을 일으키고 날개를 펼침, 고양이가 고삐를 쥐고 머리 위에 탑승",
         "action": "드래곤 일어섬, 날개 전개, 고양이가 고삐를 당김",
         "line": "없음", "trans": "하드컷", "sfx": "날개 펼침 휘익, 고삐 가죽 소리",
         "models": "Seedance / Veo",
         "img": f"low ground-level view, {DRAGON} rising with wings unfolding, a tiny kitten knight riding on its head holding leather reins, ivory cape fluttering",
         "vid": "the dragon rises and unfolds its wings, the kitten pulls the reins; camera still on the ground",
         "ani": f"low ground-level view, {DRAGON} rising with wings unfolding, a tiny armored {{ANIMAL}} riding on its head holding leather reins"},
        {"t0": 20.1, "t1": 21.8, "size": "MS", "angle": "로우", "move": "고정", "grid": "1,4,7",
         "comp": "드래곤 머리+안장+고양이가 화면 중앙, 날개가 상하로 꽉 참",
         "action": "이륙 직전 날갯짓 1회",
         "line": "없음", "trans": "하드컷", "sfx": "20.85s 큰 날갯짓",
         "models": "Kling (날갯짓 반동)",
         "img": f"low angle, {DRAGON} with a small saddle and reins, the kitten knight seated on its head, wings raised high, about to take off",
         "vid": "one powerful wing flap, dust and grass blown back, the dragon lifts slightly off the ground",
         "ani": f"low angle, {DRAGON} with a saddle, the armored {{ANIMAL}} knight seated on its head, wings raised, about to take off"},
        {"t0": 21.8, "t1": 26.0, "size": "EWS (하늘)", "angle": "정 로우 (하늘 올려다봄)", "move": "고정, 대상이 멀어짐", "grid": "1,4,7",
         "comp": "하얀 하늘 배경에 드래곤 배쪽 실루엣, 날개가 화면을 가로지르다 점점 작아짐",
         "action": "드래곤이 카메라 위를 지나 날아가며 멀어짐 → 끝",
         "line": "없음", "trans": "엔딩 (실루엣)", "sfx": "날갯짓이 멀어짐(24.95/25.75s), 바람",
         "models": "Veo / Seedance (대기 원근·실루엣)",
         "img": f"view straight up from the ground at a pale overcast sky, the underside silhouette of {DRAGON} flying overhead with wings fully spread, tiny rider on its head",
         "vid": "the dragon flies over the camera and recedes into the white sky, wings beating slowly, getting smaller",
         "ani": f"view straight up at a pale sky, silhouette of {DRAGON} flying overhead with a tiny {{ANIMAL}} rider on its head"},
    ],
    "cast": [("아기고양이 기사", "{ANIMAL} 기사 (1위와 동일 캐릭터 시트 사용)"), ("붉은 드래곤", "동일 드래곤 유지 (시리즈 연속성)")],
    "rotate": True,
}
