"""Romance drama — 90s-film wedding betrayal twist (dreamfall.art, 'Across the Street – Part 5')."""
from common import VERTICAL

BRIDE = [["원본: 90년대 금발 신부(사람)", "a 1990s supermodel-like blonde bride"],
         ["흰 페르시안 고양이 신부", "an elegant white Persian cat bride standing upright"],
         ["골든 햄스터 신부", "an elegant golden hamster bride standing upright"],
         ["흰 토끼 신부", "an elegant white lop-eared bunny bride standing upright"],
         ["사모예드 신부", "an elegant fluffy white Samoyed bride standing upright"]]
GROOM = [["원본: 흑발 신랑(사람)", "a handsome 1990s dark-haired groom"],
         ["턱시도 고양이 신랑", "a handsome black-and-white tuxedo cat groom standing upright"],
         ["햄스터 신랑", "a handsome dark-brown hamster groom standing upright"],
         ["코기 신랑", "a handsome Pembroke Welsh corgi groom standing upright"],
         ["검은 토끼 신랑", "a handsome black bunny groom standing upright"]]
OTHER = [["원본: 흑갈색 머리 '그 여자'(사람)", "a stunning 1990s brunette woman with long voluminous blowout hair"],
         ["샴 고양이 '그 여자'", "a stunning sleek Siamese cat woman standing upright"],
         ["친칠라 '그 여자'", "a stunning grey chinchilla woman standing upright"],
         ["레서판다 '그 여자'", "a stunning red panda woman standing upright"],
         ["검은 고양이 '그 여자'", "a stunning glossy black cat woman standing upright"]]

A = ("{{A}} with a high chignon, a sparkling diamond tiara, long tulle veil, long-sleeve ivory lace wedding gown with a "
     "sweetheart neckline, layered diamond necklace, glossy nude-red lips")
B = "{{B}} with slicked-back hair, black tuxedo, black bow tie, white pleated shirt, white rose boutonniere"
C = ("{{C}} in a midnight-navy satin off-shoulder gown with draped sleeves, statement diamond V necklace, long diamond "
     "drop earrings, rosy lips")
PRIEST = "an older priest in black robes with a gold embroidered stole"
SET = ("grand gothic cathedral wedding: tall stained-glass windows, candelabras with lit candles, white rose and baby's "
       "breath arrangements at the altar, carved wooden pews filled with 1990s-dressed guests")
LOOK = ("1990s romantic drama film still, shot on 35mm Kodak Vision3 500T, soft halation, fine film grain, warm "
        "tungsten candlelight mixed with cool stained-glass daylight, shallow depth of field, 50mm anamorphic-feel "
        "lens, " + VERTICAL)

M_DIALOG = [("google veo-3-1", "대사 립싱크+목소리까지 네이티브 생성, 90s 필름룩 우수"),
            ("kling-v3-omni", "캐릭터 레퍼런스 고정 + 립싱크, 27컷 얼굴 일관성 1위"),
            ("seedance-2-0", "멀티샷 일관성·감정 연기")]
M_REACT = [("minimax-h3", "하객 표정 리액션(놀람·경멸) 미세 연기"), ("kling-v3", "군중 인물 일관성"),
           ("hailuo-2-3-fast", "짧은 컷 가성비")]
M_INSERT = [("kling-v3", "손·반지 인서트 디테일 최강"), ("google veo-3-1", "보석 반사광"), ("seedance-2-0", "정교한 손 동작")]
M_WIDE = [("seedance-2-0", "와이드 동선·걷기+카메라 무브"), ("kling-v3", "드레스 자락 물리"), ("google veo-3-1", "성당 스케일·빛")]


def shot(t0, t1, name, frames, size, angle, move, comp, action, line, audio, img, vid, models):
    return {"t0": t0, "t1": t1, "name": name, "frames": frames, "size": size, "angle": angle, "move": move,
            "comp": comp, "action": action, "line": line, "audio": audio, "trans": "cut",
            "trans_note": "하드컷 (대사/시선 기준 편집점)",
            "img": f"{img} {SET}. {LOOK}.", "vid": f"{vid} {LOOK}.", "models": models}


SHOTS = [
    shot(0.0, 1.83, "'그 여자' 등장 — 하객석에서 옆눈질", [0.9], "미디엄 클로즈업", "눈높이", "고정",
         "그 여자 정중앙, 얼굴 세로 30~40%, 목걸이 세로 58%. 뒤로 흐린 하객들, 우하단 신도석 리본.",
         "고개를 살짝 돌려 제단 쪽을 곁눈질, 입꼬리에 여유로운 미소.", "없음", "오르간/현악 웨딩 앰비언스",
         f"{C}, seated in a church pew among guests, glancing sideways toward the altar with a knowing half-smile.",
         f"{C} sits in a pew and slowly glances sideways toward the altar with a knowing half-smile. Static camera.", M_REACT),
    shot(1.83, 3.27, "제단 위 신랑·신부 — 신부가 뒤돌아봄", [2.5], "풀샷 투샷 (신부 좌·신랑 우·신부님 중앙)", "눈높이 정면", "고정",
         "신부 가로 25%(관객 쪽으로 고개), 신랑 가로 75%(신부 손 잡음), 신부님 가로 45% 뒤. 중앙에 흰 꽃 장식, 스테인드글라스 상단.",
         "신랑이 반지 끼워주려는데 신부는 뒤돌아 하객석(카메라 쪽)을 차갑게 봄.", "없음", "앰비언스",
         f"{A} and {B} at the altar holding hands, the bride turning her head coldly toward the guests while the groom smiles at her, {PRIEST} behind them.",
         f"{B} holds {A}'s hand smiling; {A} turns her head away toward the guests with a cold stare; {PRIEST} waits. Static.", M_DIALOG),
    shot(3.27, 4.23, "인서트 — 반지 끼우는 손", [3.7], "익스트림 클로즈업 인서트", "약간 위", "고정",
         "두 손이 화면 중앙 대각선, 반지가 가로 50%·세로 40%. 배경 흰 장미 보케.",
         "신랑이 신부 약지에 다이아 반지를 밀어 넣음.", "대사 시작(신부, 화면 밖 목소리 = J컷)", "대사",
         "Extreme close-up of a groom's hand sliding a diamond engagement ring onto a bride's ring finger, white roses blurred behind.",
         "Extreme close-up: the groom slides a diamond ring onto the bride's finger, fingers trembling slightly.", M_INSERT),
    shot(4.23, 5.97, "신부의 폭로 (1)", [5.1], "풀샷 투샷", "눈높이 정면", "고정",
         "#2와 같은 구도(구도 반복 = 같은 공간 인지). 신부가 신랑 쪽으로 몸을 돌림.",
         "신부가 신랑을 똑바로 보며 폭로 대사, 신랑은 반지를 든 채 굳음.", "신부: 어젯밤, 당신 누구랑 있었어? (원본 비트: '어제 다른 여자랑 있었지')", "대사",
         f"{A} turning to face {B} at the altar, accusing him, the groom frozen holding the ring, {PRIEST} behind.",
         f"{A} turns to {B} and says her accusation with a calm cold voice; {B} freezes holding the ring. Static.", M_DIALOG),
    shot(5.97, 7.6, "하객 리액션 — 웅성", [6.8], "미디엄샷 (하객 2~3명)", "눈높이", "고정",
         "전경 좌측 남자 하객(가로 40%), 뒤 검은 스팽글 드레스 여자 하객 우측(가로 75%). 모두 제단 쪽 응시.",
         "하객들이 놀라 서로 쳐다보거나 제단을 응시.", "신부: 거짓말쟁이.", "하객 웅성",
         "1990s wedding guests in a pew reacting with shock, a man in a suit holding a program, a brunette woman in a black sequined dress staring.",
         "Wedding guests turn their heads in shock toward the altar, murmuring. Static.", M_REACT),
    shot(7.6, 8.83, "'그 여자' — 입술 깨물기", [8.2], "미디엄 클로즈업 정면", "눈높이", "고정",
         "얼굴 정중앙 세로 30%, 목걸이 세로 58%. 좌우 흐린 하객.",
         "들킨 듯 입술을 살짝 깨물고 태연한 척.", "없음", "대사 이어짐",
         f"{C}, seated in a pew facing forward, biting her lip with a guilty but composed expression.",
         f"{C} bites her lower lip, trying to look calm. Static.", M_REACT),
    shot(8.83, 10.13, "하객(검은 재킷 여자) 고개 돌림", [9.5], "미디엄샷", "눈높이", "고정",
         "검은 블레이저 여자 하객 가로 45%, 좌하단에 그 여자의 어깨·목걸이 일부(전경).",
         "하객이 그 여자 쪽으로 고개를 휙 돌림.", "신부: 저기, 본인한테 물어봐.", "대사",
         "A wedding guest in a black blazer turning her head toward the woman in the navy gown sitting beside her.",
         "A guest in a black blazer turns her head sharply toward the woman in navy. Static.", M_REACT),
    shot(10.13, 12.63, "신랑 어깨 너머 → 하객석의 그 여자 (OTS)", [11.4], "오버더숄더 미디엄샷", "눈높이", "고정",
         "좌측 40%를 신랑 뒷머리·어깨(흐림)가 차지, 그 여자는 가로 60%·세로 40%에 선명. 하객들 뒤.",
         "신랑이 그 여자를 바라보고, 그 여자도 신랑을 마주 봄.", "없음", "정적",
         f"Over-the-shoulder from behind {B} (blurred foreground left) toward {C} seated in the pews holding a program, staring back.",
         f"Over-the-shoulder shot: {B} looks at {C} in the pews; she holds his gaze. Static, rack focus stays on her.", M_DIALOG),
    shot(12.63, 14.33, "그 여자 클로즈업 (신랑 시점)", [13.5], "클로즈업", "눈높이", "아주 느린 푸시인",
         "얼굴이 화면 상단 55%, 눈 세로 33%. 배경 완전 보케.",
         "입술을 살짝 벌리고 카메라(신랑)를 정면으로 응시.", "신랑: 저 사람이 왜 여기 있어?", "대사",
         f"Close-up of {C} looking straight into the lens, lips slightly parted, bokeh of the cathedral behind.",
         f"Close-up of {C} staring into the lens, lips parted, very slow push-in.", M_DIALOG),
    {**shot(14.33, 21.2, "신랑·신부 밀착 언쟁 (롱테이크)", [15.0, 17.5, 20.3], "타이트 투샷 프로필", "눈높이", "고정 + 미세 푸시인",
            "신부 좌측(가로 30%), 신랑 우측(가로 65%) 코끝이 닿을 듯 마주봄, 두 얼굴이 세로 25~45%. 뒤로 스테인드글라스.",
            "신부 차분·냉정, 신랑 당황→억울. 대사 3줄 주고받음.",
            "신부: 내가 초대했어. / 신랑: 지금 이걸 모두 앞에서 해? / 신부: 모두 앞에서 맹세하려 했으니까.", "대사 3줄",
            f"Tight profile two-shot of {A} and {B} face to face at the altar, almost touching, tense argument, stained glass behind.",
            f"{A} and {B} argue quietly face to face: she speaks calmly, he answers defensively, she replies coldly. Subtle push-in.", M_DIALOG)},
    shot(21.2, 22.4, "신랑 클로즈업 — 신부님에게", [21.8], "클로즈업 (3/4)", "눈높이", "고정",
         "신랑 얼굴 가로 60%, 좌측 전경에 신부 베일이 흐리게.",
         "신랑이 신부님 쪽으로 눈을 돌려 부탁.", "신랑: 잠시만 시간 좀 주세요.", "대사",
         f"Close-up of {B} in three-quarter view, the bride's veil soft in the foreground left, pleading glance off-screen.",
         f"{B} glances toward the priest and asks for a moment. Static.", M_DIALOG),
    shot(22.4, 25.8, "신랑 어깨 너머 신부 + 신부님", [24.0], "오버더숄더 미디엄", "눈높이", "고정",
         "신부 옆얼굴 좌측(가로 30%), 신부님 중앙 뒤, 신랑 뒷모습 우측 흐림.",
         "신부가 단호하게 거절.", "신부: 안 돼.", "대사",
         f"Over the groom's shoulder: {A} in profile on the left, firm expression, {PRIEST} in the center background.",
         f"{A} firmly refuses, jaw set; the priest watches. Static.", M_DIALOG),
    shot(25.8, 27.0, "미디엄 투샷 — 제단 십자가 사이", [26.4], "미디엄 투샷", "눈높이", "고정",
         "두 사람 프로필 좌우 대칭, 가운데 아래 금색 십자가, 위 스테인드글라스.",
         "서로 마주 본 채 침묵.", "없음", "정적",
         f"Medium profile two-shot of {A} and {B} facing each other, a gold altar cross between them, candles and stained glass behind.",
         f"{A} and {B} face each other in silence. Static.", M_DIALOG),
    shot(27.0, 28.17, "하객 리액션 2", [27.6], "미디엄샷", "눈높이", "고정",
         "좌측 남자 하객 눈 내리깜, 우측 곱슬머리 여자 하객 굳은 표정, 뒤 하객들 응시.",
         "하객들 불편한 표정.", "없음", "정적",
         "1990s wedding guests in pews looking uncomfortable, a man looking down, a curly-haired woman frowning.",
         "Guests shift uncomfortably, one man looks down. Static.", M_REACT),
    shot(28.17, 29.57, "투샷 — 로즈 윈도 역광", [28.9], "미디엄 클로즈 투샷", "눈높이", "고정",
         "신부 좌·신랑 우 프로필, 가운데 밝은 원형 스테인드글라스(역광 하이라이트).",
         "신랑이 간절하게 말함.", "신랑: 나 봐. 난 아직 너를 선택해.", "대사",
         f"Medium close profile two-shot of {A} and {B}, a glowing rose window between them, candles below.",
         f"{B} pleads earnestly to {A}. Static.", M_DIALOG),
    shot(29.57, 32.23, "신부 클로즈업", [30.9], "클로즈업", "눈높이", "고정",
         "신부 얼굴 정중앙, 티아라 상단, 눈 세로 38%, 우측 가장자리 신랑 어깨 흐림.",
         "촉촉하지만 흔들림 없는 눈빛으로 신랑을 봄.", "(신랑 대사 계속)", "대사",
         f"Close-up of {A}, tiara glinting, glossy eyes but steady, groom's shoulder blurred at the right edge.",
         f"{A} listens with steady, slightly glossy eyes. Static.", M_DIALOG),
    shot(32.23, 34.9, "투샷 — 신부의 결정타", [33.5], "미디엄 클로즈 투샷", "눈높이", "고정",
         "#15와 같은 구도.",
         "신부가 조용히 결정타 대사.", "신부: 알아. 근데 둘 다 갖고 싶었잖아.", "대사",
         f"Medium close profile two-shot of {A} and {B}, rose window between them.",
         f"{A} answers quietly with a devastating line; {B} is speechless. Static.", M_DIALOG),
    shot(34.9, 36.23, "인서트 — 반지 빼기", [35.5], "클로즈업 인서트", "약간 위", "고정",
         "신부 손이 화면 하단 중앙, 뒤로 흰 꽃다발·촛불 보케, 우측 신랑 얼굴 일부.",
         "신부가 약지에서 반지를 천천히 뺌.", "없음", "정적",
         f"Close-up of {A}'s hands slowly slipping the diamond ring off her finger, white bouquet and candles blurred behind.",
         f"{A} slowly slides the ring off her finger. Static.", M_INSERT),
    shot(36.23, 37.13, "인서트 — 신랑 손바닥 위 두 반지", [36.6], "익스트림 클로즈업", "위에서", "고정",
         "신랑 손바닥이 화면 대부분, 반지 두 개가 중앙, 우측에서 신부 손가락.",
         "신부가 반지를 신랑 손바닥에 올려놓음.", "없음", "반지 딸깍",
         "Extreme close-up of a groom's open palm holding two wedding rings, the bride's fingertips placing the second ring.",
         "The bride places her ring into the groom's open palm next to his band. Static.", M_INSERT),
    shot(37.13, 38.63, "신랑 클로즈업 — 베일 너머 멍함", [37.9], "클로즈업", "눈높이", "고정",
         "신랑 얼굴 가로 60%, 좌측 절반을 신부 베일이 흐리게 덮음.",
         "충격으로 멍하게 봄.", "없음", "정적",
         f"Close-up of {B} seen partly through the bride's soft tulle veil, stunned expression.",
         f"{B} stares, stunned, seen through the veil. Static.", M_DIALOG),
    shot(38.63, 41.77, "와이드 — 신부가 제단을 내려감", [39.5, 41.2], "와이드 풀샷 (대칭)", "눈높이", "고정",
         "성당 대칭 구도, 스테인드글라스 3개 상단, 신부가 계단 중앙을 내려옴(가로 45%), 신랑은 뒤에 서 있음.",
         "신부가 부케를 들고 계단을 내려와 관객 쪽으로 걸어옴.", "없음", "음악 시작(현악)",
         f"Symmetrical wide shot of {A} walking down the altar steps holding a white rose bouquet, {B} left standing behind, three stained-glass windows above.",
         f"{A} walks down the altar steps toward the camera with the bouquet while {B} stays behind. Static wide.", M_WIDE),
    shot(41.77, 43.93, "부케를 '그 여자'에게 건넴", [42.8], "미디엄 와이드", "하객석 높이", "고정",
         "전경 하단 하객 뒷머리, 신부 좌측(가로 30%), 일어선 그 여자 우측(가로 70%).",
         "신부가 부케를 그 여자에게 건네고, 그 여자가 일어섬.", "없음", "음악",
         f"{A} handing her white bouquet to {C}, who rises from the pew, guests' heads in the foreground.",
         f"{A} hands her bouquet to {C}, who stands up from the pew. Static.", M_WIDE),
    shot(43.93, 48.07, "두 여자가 함께 버진로드를 걸어나옴", [44.5, 46.8], "미디엄 투샷 (걷기)", "눈높이", "달리백(뒤로 이동하며 따라가기)",
         "신부 좌(가로 25%), 그 여자 우(가로 70%) 나란히, 신랑은 뒤 중앙에 작게 흐리게.",
         "두 사람이 당당하게 나란히 걸어 나옴.", "신부(그 여자에게): 약속한 대로.", "대사 + 음악",
         f"{A} and {C} walking side by side down the aisle toward the camera, {C} holding the white bouquet, {B} small and blurred at the altar behind.",
         f"{A} and {C} walk confidently down the aisle side by side toward the camera; the camera dollies back with them.", M_WIDE),
    shot(48.07, 50.13, "멈춰서 뒤돌아봄", [49.1], "미디엄 투샷", "눈높이", "고정",
         "그 여자 좌(가로 25%), 신부 우(가로 65%), 둘 다 어깨 너머로 제단 쪽을 봄. 뒤로 제단 촛불.",
         "신랑이 부르는 소리에 둘이 동시에 뒤돌아봄.", "신랑: 잠깐!", "대사",
         f"{C} and {A} stopped mid-aisle, both turning to look back over their shoulders toward the altar.",
         f"Both women stop and turn back over their shoulders at the same time. Static.", M_WIDE),
    shot(50.13, 51.33, "신랑 — 반지 든 손", [50.7], "미디엄 클로즈업", "눈높이", "고정",
         "신랑 정면 가로 40%, 좌하단에 반지 든 손, 뒤 스테인드글라스 보케.",
         "반지를 들어 올린 채 말문이 막힘.", "없음", "정적",
         f"Medium close-up of {B} alone at the altar holding up a ring, stained glass bokeh behind.",
         f"{B} holds up the ring, lost for words. Static.", M_DIALOG),
    shot(51.33, 52.17, "신부 초근접 — 펀치라인", [51.7], "익스트림 클로즈업", "눈높이", "고정",
         "얼굴이 화면 전체, 눈 세로 40%, 티아라 상단.",
         "무표정하게 펀치라인 한 마디.", "신부: 우리 둘 중 누구?", "대사",
         f"Extreme close-up of {A}, deadpan, tiara at the top of the frame.",
         f"{A} delivers a deadpan one-line punchline. Static.", M_DIALOG),
]
SHOTS.append({**shot(52.17, 52.41, "스매시 투 블랙", [52.3], "블랙", "-", "-", "검은 화면 0.24초", "대사 직후 바로 암전",
                     "없음", "무음", "Pure black frame.", "Pure black frame, silence.", []),
              "trans": "end", "black": True, "trans_note": "펀치라인 직후 암전 = 여운 + 다음 편(Part 6) 궁금증"})

VIDEO = {
    "id": 1, "page": "p1_romance_wedding_twist.html", "short": "① 로맨스 결혼식 반전",
    "rank_label": "로맨스 · 드라마 시리즈",
    "title": "결혼식 제단에서 폭로 → 신부가 '그 여자'와 함께 떠나는 반전",
    "creator": "Maria Rubtsova @dreamfall.art — 'ACROSS THE STREET – PART 5'", "url": "https://www.instagram.com/p/Ddjay5KNkF6/",
    "likes": 348033, "comments": 3314, "date": "2026-09-21", "duration": 52.41, "res": "1440×2560", "fps": 30,
    "model_guess": "1440×2560 업스케일 + 대사 립싱크가 들어간 90년대 필름룩 → 이미지(미드저니 계열) + Veo 3 계열 대사 생성 또는 Kling 립싱크 조합으로 추정. 시리즈물(Part 5).",
    "caption": "'ACROSS THE STREET – PART 5' + 'DREAM 댓글 달면 프롬프트 보내줌' (댓글 유도 CTA → 댓글 3,314)",
    "hook": "0초: 하객석의 아름다운 '그 여자'가 옆눈질로 제단을 봄 → 1.8초: 신부가 반지를 받으며 차갑게 뒤돌아봄. 두 컷 만에 '삼각관계'가 보임.",
    "formula": "긴장 설정(0~10초) → 폭로·언쟁 샷/리버스샷(10~35초) → 반지 반납(35~38초) → 두 여자가 함께 퇴장(38~50초) → 펀치라인 + 암전(51~52초)",
    "viral": [
        "90년대 로맨스 영화 스틸 같은 필름룩 = '이거 무슨 영화야?' 댓글 유도.",
        "평균 컷 길이 1.9초 · 27컷 → 대사 드라마인데도 숏폼 속도.",
        "반전 2단: ① 신부가 바람 상대를 직접 초대 ② 둘이 함께 떠남 + 마지막 한 마디.",
        "시리즈 제목(Part 5) + 댓글 키워드 CTA → 이전/다음 편 탐색 & 댓글 폭발.",
        "샷/리버스샷 + 하객 리액션 컷 = 시청자가 '하객 입장'에서 구경하는 몰입.",
        "마지막 0.24초 블랙 = 여운 + 루프 시 첫 컷(그 여자 옆눈질)이 복선처럼 다시 보임.",
    ],
    "look": [
        ("화면비/해상도", "9:16, 원본 1440×2560 30fps (1080×1920 제작 후 업스케일)"),
        ("필름 룩", "35mm 코닥 500T 느낌: 할레이션(빛 번짐), 고운 그레인, 살짝 낮은 대비의 따뜻한 피부톤, 스테인드글라스의 차가운 블루"),
        ("렌즈/심도", "클로즈업 85mm 느낌 얕은 심도, 투샷 50mm, 와이드 35mm. 배경 촛불 보케"),
        ("카메라", "거의 전부 고정(삼각대) — 드라마 문법. 움직이는 컷은 #9 푸시인, #23 달리백 두 개뿐"),
        ("편집 문법", "샷/리버스샷, 오버더숄더, 인서트(반지), 리액션 컷, 180도 규칙 유지(신부 항상 좌측)"),
        ("색 팔레트", "아이보리 레이스 · 미드나잇 네이비 #1B2340 · 촛불 앰버 #E7A55A · 스테인드글라스 코발트 #2E4FA0 · 립 레드"),
        ("인물 배치 규칙", "신부 = 화면 좌측, 신랑 = 우측(180도 라인), 그 여자 = 하객석(화면 중앙)"),
    ],
    "slots": {"A": {"label": "신부", "default": BRIDE[0][1], "options": BRIDE},
              "B": {"label": "신랑", "default": GROOM[0][1], "options": GROOM},
              "C": {"label": "그 여자", "default": OTHER[0][1], "options": OTHER}},
    "characters": [("신부 (공통)", A), ("신랑 (공통)", B), ("그 여자 (공통)", C), ("신부님", PRIEST), ("세트", SET), ("룩", LOOK)],
    "negative": "modern smartphone look, oversharpened, HDR, cartoon, text, subtitles, watermark, extra fingers, "
                "deformed hands, face morphing between shots, crossing the 180-degree line",
    "swaps": [
        ["사람 → 동물 커플", "동물로 바꾸면 '드레스 입은 동물'의 귀여움 + 막장 드라마 대사 = 갭 코미디로 더 강해짐. 90s 필름룩은 그대로 유지."],
        ["신부=흰 동물 / 그 여자=짙은 색 동물", "원본의 '아이보리 vs 네이비' 색 대비를 털 색으로 유지하면 누가 누군지 컷마다 바로 구분됨."],
        ["손 인서트(#3, #18, #19)", "동물 앞발로 바꾸면 반지가 안 맞음 → '작은 앞발 발가락에 반지(ring on a tiny paw toe)' 명시, 반지 크기 'tiny'."],
        ["립싱크", "동물 입모양 립싱크는 Kling Omni/Veo 3.1이 가장 자연스러움. 대사는 짧게(1컷 1문장)."],
        ["대사", "아래 자막(SRT)은 원본 대사를 복사하지 않고 같은 흐름으로 새로 쓴 한국어/영어 대사. 필요하면 톤만 수정."],
    ],
    "shots": SHOTS,
    "audio": {
        "bgm": "대사 중심 드라마(영어 대사 확인). 0~38초는 성당 앰비언스 + 조용한 현악 패드 위에 대사, 38초 신부 퇴장부터 로맨틱 현악 테마가 올라옴, 52초 암전과 동시에 무음.",
        "bpm": "음악은 박자감 없는 앰비언트/현악 (측정값 172는 대사 음절 영향 — 의미 없음)",
        "mix": "대사 -12 LUFS 근처 앞, 앰비언스 -28dB, 음악 -22dB → 38초부터 음악 -16dB로 올림. 컷마다 대사 앞 0.2초 J컷(목소리가 먼저 들어옴).",
        "music_prompt": "Melancholic 1990s romantic drama film score, solo piano with soft string quartet, slow rubato, "
                        "cathedral reverb, bittersweet and elegant, builds gently in the last 15 seconds, 52 seconds, no vocals",
        "bgm_db": -18,
        "sfx": [
            (0.0, "성당 앰비언스(웅성·기침·오르간 잔향)", "large cathedral interior ambience, soft murmurs of seated guests, distant organ reverb"),
            (3.4, "반지 끼우는 미세음", "tiny metallic ring slide, close foley"),
            (6.0, "하객 웅성", "shocked crowd gasp and murmur in a church"),
            (36.3, "반지 딸깍", "small ring clink dropped into a palm"),
            (38.7, "드레스 자락 + 발소리", "wedding dress fabric rustle and heels on stone steps"),
            (44.0, "하객석 웅성 커짐", "church crowd whispering louder"),
            (52.17, "암전 무음 컷", "silence (hard cut)"),
        ],
    },
    "edit_terms": [
        ("샷/리버스샷 (Shot–reverse shot)", "대사하는 사람 ↔ 듣는 사람 번갈아. #9↔#8, #15↔#16."),
        ("180도 규칙", "신부 항상 좌측, 신랑 우측 — 27컷 내내 유지해서 혼란 없음."),
        ("오버더숄더 (OTS)", "#8, #12: 한 인물 어깨 너머로 상대를 봄 → 관계·거리감."),
        ("인서트 (Insert)", "#3 반지 끼우기, #18 반지 빼기, #19 손바닥 위 두 반지 = 스토리를 물건으로 요약."),
        ("리액션 컷 (Reaction shot)", "#5, #7, #14 하객 표정 = 관객 대리 감정."),
        ("J컷 (J-cut)", "다음 컷 대사가 이전 컷 끝에서 먼저 들림 → 컷이 부드러움."),
        ("구도 반복 (Repeated framing)", "#2와 #4, #15와 #17 같은 구도 → 변화(표정·대사)만 눈에 들어옴."),
        ("스매시 투 블랙 (Smash to black)", "펀치라인 직후 0.24초 암전 → 여운·다음 편 궁금증."),
        ("페이싱", "27컷 / 평균 1.94초, 최장 #10 6.9초(언쟁 롱테이크)로 호흡 조절."),
    ],
    "grade": ("eq=contrast=1.06:saturation=0.95:gamma=0.98,colorbalance=rs=0.04:gs=0.01:bs=-0.03:rh=0.03:bh=-0.02,"
              "noise=alls=7:allf=t,vignette=PI/5"),
    "grade_note": "90년대 필름: 채도 약간 낮춤, 섀도에 따뜻한 레드, 하이라이트 살짝 앰버, 시간축 그레인(noise allf=t), 비네팅. 할레이션을 더 원하면 split→gblur→blend=screen으로 하이라이트 번짐 추가.",
    "subs": [
        (3.3, 5.9, "어젯밤, 당신 누구랑 있었어?\nWhere were you last night — and with whom?"),
        (6.0, 7.5, "거짓말쟁이.\nLiar."),
        (8.9, 10.1, "저기, 본인한테 물어봐.\nGo ahead. Ask her."),
        (12.7, 14.3, "저 사람이 왜 여기 있어?\nWhy is she here?"),
        (15.0, 16.2, "내가 초대했어.\nShe's my guest."),
        (16.3, 18.1, "지금 이걸 모두 앞에서 해?\nHere? In front of everyone?"),
        (18.2, 21.0, "모두 앞에서 맹세하려 했으니까.\nYou were about to vow in front of everyone."),
        (21.2, 22.4, "잠시만 시간 좀 주세요.\nCould we have a moment?"),
        (22.6, 24.5, "안 돼.\nNo."),
        (28.2, 29.6, "나 봐. 난 아직 너를 선택해.\nLook at me. I still choose you."),
        (32.3, 34.9, "알아. 근데 둘 다 갖고 싶었잖아.\nI know. You just wanted both."),
        (44.0, 46.0, "약속한 대로.\nJust like we planned."),
        (47.0, 48.3, "잠깐!\nWait!"),
        (51.33, 52.17, "우리 둘 중 누구?\nWhich of us?"),
    ],
    "strip_step": 1.0,
    "checklist": [
        "인물 3명(신부·신랑·그 여자) 캐릭터 시트를 먼저 만들고 27컷 전부 레퍼런스로 입력",
        "180도 라인: 신부 좌·신랑 우 절대 바꾸지 않기",
        "27컷 길이를 ⑧ 표대로 정확히 트림 (평균 1.94초)",
        "대사 컷은 Veo 3.1 / Kling Omni 립싱크, 하객·인서트는 저렴한 모델",
        "자막 SRT는 하단 중앙, 흰 글씨 검은 외곽선 (fonts/ 폴더에 Pretendard-Bold.ttf)",
        "필름 그레인·비네팅 색보정 일괄 적용",
        "마지막 0.24초 블랙 + 캡션에 시리즈명·댓글 키워드 CTA",
    ],
    "cc_prompt": "너는 세계 최고의 숏폼 드라마 감독 겸 편집자다. 레퍼런스 '결혼식 반전(52초, 27컷)'을 신부 {{A}}, 신랑 {{B}}, 그 여자 {{C}} 로 똑같은 컷 구성·타이밍으로 만든다.\n"
                 "1) 캐릭터 시트 3장 + 성당 세트 1장 (midjourney-v8 필름룩 또는 nano-banana-pro).\n"
                 "2) 27컷 첫 프레임 이미지: ⑥의 컷별 이미지 프롬프트, 세 캐릭터 시트를 레퍼런스로.\n"
                 "3) 영상: 대사 컷 = veo-3-1 또는 kling-v3-omni(립싱크, 대사는 subs.srt 문장), 리액션 = minimax-h3, 인서트 = kling-v3, 와이드 = seedance-2-0. clips/shot01~27.mp4 저장.\n"
                 "4) 사운드: ⑦ 음악 프롬프트 + 효과음 7개, 대사는 모델 네이티브 음성 또는 ElevenLabs.\n"
                 "5) 편집: ⑧ build.sh + subs.srt 실행 (fonts/Pretendard-Bold.ttf 필요).\n"
                 "6) 원본과 컷 길이 오차 ±0.1초, 180도 라인 유지 검증 리포트.\n"
                 "🔴 승인 전 업로드 금지. 수정 가능 범위: 작업 폴더의 clips/, audio/, sfx/, fonts/, build.sh, subs.srt.",
}
